let data = [
	{ name: "Bulbasaur", id: "bulbasaur", type1: "Grass", type2: "Poison" },
	{ name: "Ivysaur", id: "ivysaur", type1: "Grass", type2: "Poison" },
	{ name: "Venusaur", id: "venusaur", type1: "Grass", type2: "Poison" },
	{
		name: "Mega Venusaur",
		id: "venusaur-mega",
		type1: "Grass",
		type2: "Poison",
	},
	{
		name: "Gigantamax Venusaur",
		id: "gigantamax venusaur",
		type1: "Grass",
		type2: "Poison",
	},
	{ name: "Charmander", id: "charmander", type1: "Fire", type2: "" },
	{ name: "Charmeleon", id: "charmeleon", type1: "Fire", type2: "" },
	{ name: "Charizard", id: "charizard", type1: "Fire", type2: "Flying" },
	{
		name: "Mega Charizard X",
		id: "charizard-megax",
		type1: "Fire",
		type2: "Dragon",
	},
	{
		name: "Mega Charizard Y",
		id: "charizard-megay",
		type1: "Fire",
		type2: "Flying",
	},
	{
		name: "Gigantamax Charizard",
		id: "charizard-gmax",
		type1: "Fire",
		type2: "Flying",
	},
	{ name: "Squirtle", id: "squirtle", type1: "Water", type2: "" },
	{ name: "Wartortle", id: "wartortle", type1: "Water", type2: "" },
	{ name: "Blastoise", id: "blastoise", type1: "Water", type2: "" },
	{ name: "Mega Blastoise", id: "mega blastoise", type1: "Water", type2: "" },
	{
		name: "Gigantamax Blastoise",
		id: "gigantamax blastoise",
		type1: "Water",
		type2: "",
	},
	{ name: "Caterpie", id: "caterpie", type1: "Bug", type2: "" },
	{ name: "Metapod", id: "metapod", type1: "Bug", type2: "" },
	{ name: "Butterfree", id: "butterfree", type1: "Bug", type2: "Flying" },
	{
		name: "Gigantamax Butterfree",
		id: "gigantamax butterfree",
		type1: "Bug",
		type2: "",
	},
	{ name: "Weedle", id: "weedle", type1: "Bug", type2: "Poison" },
	{ name: "Kakuna", id: "kakuna", type1: "Bug", type2: "Poison" },
	{ name: "Beedrill", id: "beedrill", type1: "Bug", type2: "Poison" },
	{ name: "Mega Beedrill", id: "mega beedrill", type1: "Bug", type2: "Poison" },
	{ name: "Pidgey", id: "pidgey", type1: "Normal", type2: "Flying" },
	{ name: "Pidgeotto", id: "pidgeotto", type1: "Normal", type2: "Flying" },
	{ name: "Pidgeot", id: "pidgeot", type1: "Normal", type2: "Flying" },
	{
		name: "Mega Pidgeot",
		id: "mega pidgeot",
		type1: "Normal",
		type2: "Flying",
	},
	{ name: "Rattata", id: "rattata", type1: "Normal", type2: "" },
	{
		name: "Alolan Rattata",
		id: "alolan rattata",
		type1: "Dark",
		type2: "Normal",
	},
	{ name: "Raticate", id: "raticate", type1: "Normal", type2: "" },
	{
		name: "Alolan Raticate",
		id: "alolan raticate",
		type1: "Dark",
		type2: "Normal",
	},
	{ name: "Spearow", id: "spearow", type1: "Normal", type2: "Flying" },
	{ name: "Fearow", id: "fearow", type1: "Normal", type2: "Flying" },
	{ name: "Ekans", id: "ekans", type1: "Poison", type2: "" },
	{ name: "Arbok", id: "arbok", type1: "Poison", type2: "" },
	{ name: "Pikachu", id: "pikachu", type1: "Electric", type2: "" },
	{
		name: "Cosplay Pikachu",
		id: "cosplay pikachu",
		type1: "Electric",
		type2: "",
	},
	{
		name: "Partner Pikachu",
		id: "partner pikachu",
		type1: "Electric",
		type2: "",
	},
	{
		name: "Gigantamax Pikachu",
		id: "gigantamax pikachu",
		type1: "Electric",
		type2: "",
	},
	{ name: "Pikachu Libre", id: "pikachu libre", type1: "", type2: "" },
	{ name: "Raichu", id: "raichu", type1: "Electric", type2: "" },
	{
		name: "Alolan Raichu",
		id: "alolan raichu",
		type1: "Electric",
		type2: "Psychic",
	},
	{ name: "Sandshrew", id: "sandshrew", type1: "Ground", type2: "" },
	{
		name: "Alolan Sandshrew",
		id: "alolan sandshrew",
		type1: "Ice",
		type2: "Steel",
	},
	{ name: "Sandslash", id: "sandslash", type1: "Ground", type2: "" },
	{
		name: "Alolan Sandslash",
		id: "alolan sandslash",
		type1: "Ice",
		type2: "Steel",
	},
	{ name: "Nidoran♀", id: "nidoran♀", type1: "Poison", type2: "" },
	{ name: "Nidorina", id: "nidorina", type1: "Poison", type2: "" },
	{ name: "Nidoqueen", id: "nidoqueen", type1: "Poison", type2: "Ground" },
	{ name: "Nidoran♂", id: "nidoran♂", type1: "Poison", type2: "" },
	{ name: "Nidorino", id: "nidorino", type1: "Poison", type2: "" },
	{ name: "Nidoking", id: "nidoking", type1: "Poison", type2: "Ground" },
	{ name: "Clefairy", id: "clefairy", type1: "Fairy", type2: "" },
	{ name: "Clefable", id: "clefable", type1: "Fairy", type2: "" },
	{ name: "Vulpix", id: "vulpix", type1: "Fire", type2: "" },
	{
		name: "Alolan Vulpix [Keokeo]",
		id: "alolan vulpix [keokeo]",
		type1: "Ice",
		type2: "",
	},
	{ name: "Ninetales", id: "ninetales", type1: "Fire", type2: "" },
	{
		name: "Alolan Ninetales",
		id: "alolan ninetales",
		type1: "Ice",
		type2: "Fairy",
	},
	{ name: "Jigglypuff", id: "jigglypuff", type1: "Normal", type2: "Fairy" },
	{ name: "Wigglytuff", id: "wigglytuff", type1: "Normal", type2: "Fairy" },
	{ name: "Zubat", id: "zubat", type1: "Poison", type2: "Flying" },
	{ name: "Golbat", id: "golbat", type1: "Poison", type2: "Flying" },
	{ name: "Oddish", id: "oddish", type1: "Grass", type2: "Poison" },
	{ name: "Gloom", id: "gloom", type1: "Grass", type2: "Poison" },
	{ name: "Vileplume", id: "vileplume", type1: "Grass", type2: "Poison" },
	{ name: "Paras", id: "paras", type1: "Bug", type2: "Grass" },
	{ name: "Parasect", id: "parasect", type1: "Bug", type2: "Grass" },
	{ name: "Venonat", id: "venonat", type1: "Bug", type2: "Poison" },
	{ name: "Venomoth", id: "venomoth", type1: "Bug", type2: "Poison" },
	{ name: "Diglett", id: "diglett", type1: "Ground", type2: "" },
	{
		name: "Alolan Diglett",
		id: "alolan diglett",
		type1: "Ground",
		type2: "Steel",
	},
	{ name: "Dugtrio", id: "dugtrio", type1: "Ground", type2: "" },
	{
		name: "Alolan Dugtrio",
		id: "alolan dugtrio",
		type1: "Ground",
		type2: "Steel",
	},
	{ name: "Meowth", id: "meowth", type1: "Normal", type2: "" },
	{ name: "Alolan Meowth", id: "alolan meowth", type1: "Dark", type2: "" },
	{ name: "Galarian Meowth", id: "galarian meowth", type1: "Steel", type2: "" },
	{
		name: "Gigantamax Meowth",
		id: "gigantamax meowth",
		type1: "Normal",
		type2: "",
	},
	{ name: "Persian", id: "persian", type1: "Normal", type2: "" },
	{ name: "Alolan Persian", id: "alolan persian", type1: "Dark", type2: "" },
	{ name: "Psyduck", id: "psyduck", type1: "Water", type2: "" },
	{ name: "Golduck", id: "golduck", type1: "Water", type2: "" },
	{ name: "Mankey", id: "mankey", type1: "Fighting", type2: "" },
	{ name: "Primeape", id: "primeape", type1: "Fighting", type2: "" },
	{ name: "Growlithe", id: "growlithe", type1: "Fire", type2: "" },
	{ name: "Arcanine", id: "arcanine", type1: "Fire", type2: "" },
	{ name: "Poliwag", id: "poliwag", type1: "Water", type2: "" },
	{ name: "Poliwhirl", id: "poliwhirl", type1: "Water", type2: "" },
	{ name: "Poliwrath", id: "poliwrath", type1: "Water", type2: "Fighting" },
	{ name: "Abra", id: "abra", type1: "Psychic", type2: "" },
	{ name: "Kadabra", id: "kadabra", type1: "Psychic", type2: "" },
	{ name: "Alakazam", id: "alakazam", type1: "Psychic", type2: "" },
	{ name: "Mega Alakazam", id: "mega alakazam", type1: "Psychic", type2: "" },
	{ name: "Machop", id: "machop", type1: "Fighting", type2: "" },
	{ name: "Machoke", id: "machoke", type1: "Fighting", type2: "" },
	{ name: "Machamp", id: "machamp", type1: "Fighting", type2: "" },
	{
		name: "Gigantamax Machamp",
		id: "gigantamax machamp",
		type1: "Fighting",
		type2: "",
	},
	{ name: "Bellsprout", id: "bellsprout", type1: "Grass", type2: "Poison" },
	{ name: "Weepinbell", id: "weepinbell", type1: "Grass", type2: "Poison" },
	{ name: "Victreebel", id: "victreebel", type1: "Grass", type2: "Poison" },
	{ name: "Tentacool", id: "tentacool", type1: "Water", type2: "Poison" },
	{ name: "Tentacruel", id: "tentacruel", type1: "Water", type2: "Poison" },
	{ name: "Geodude", id: "geodude", type1: "Rock", type2: "Ground" },
	{
		name: "Alolan Geodude",
		id: "alolan geodude",
		type1: "Rock",
		type2: "Electric",
	},
	{ name: "Graveler", id: "graveler", type1: "Rock", type2: "Ground" },
	{
		name: "Alolan Graveler",
		id: "alolan graveler",
		type1: "Rock",
		type2: "Electric",
	},
	{ name: "Golem", id: "golem", type1: "Rock", type2: "Ground" },
	{
		name: "Alolan Golem",
		id: "alolan golem",
		type1: "Rock",
		type2: "Electric",
	},
	{ name: "Ponyta", id: "ponyta", type1: "Fire", type2: "" },
	{
		name: "Galarian Ponyta",
		id: "galarian ponyta",
		type1: "Psychic",
		type2: "",
	},
	{ name: "Rapidash", id: "rapidash", type1: "Fire", type2: "" },
	{
		name: "Galarian Rapidash",
		id: "galarian rapidash",
		type1: "Psychic",
		type2: "Fairy",
	},
	{ name: "Slowpoke", id: "slowpoke", type1: "Water", type2: "Psychic" },
	{
		name: "Galarian Slowpoke",
		id: "galarian slowpoke",
		type1: "Psychic",
		type2: "",
	},
	{ name: "Slowbro", id: "slowbro", type1: "Water", type2: "Psychic" },
	{
		name: "Mega Slowbro",
		id: "mega slowbro",
		type1: "Water",
		type2: "Psychic",
	},
	{
		name: "Galarian Slowbro",
		id: "galarian slowbro",
		type1: "Poison",
		type2: "Psychic",
	},
	{ name: "Magnemite", id: "magnemite", type1: "Electric", type2: "Steel" },
	{ name: "Magneton", id: "magneton", type1: "Electric", type2: "Steel" },
	{ name: "Farfetch'd", id: "farfetch'd", type1: "Normal", type2: "Flying" },
	{
		name: "Galarian Farftech'd",
		id: "galarian farftech'd",
		type1: "Fighting",
		type2: "",
	},
	{ name: "Doduo", id: "doduo", type1: "Normal", type2: "Flying" },
	{ name: "Dodrio", id: "dodrio", type1: "Normal", type2: "Flying" },
	{ name: "Seel", id: "seel", type1: "Water", type2: "" },
	{ name: "Dewgong", id: "dewgong", type1: "Water", type2: "Ice" },
	{ name: "Grimer", id: "grimer", type1: "Poison", type2: "" },
	{
		name: "Alolan Grimer",
		id: "alolan grimer",
		type1: "Poison",
		type2: "Dark",
	},
	{ name: "Muk", id: "muk", type1: "Poison", type2: "" },
	{ name: "Alolan Muk", id: "alolan muk", type1: "Poison", type2: "Dark" },
	{ name: "Shellder", id: "shellder", type1: "Water", type2: "" },
	{ name: "Cloyster", id: "cloyster", type1: "Water", type2: "Ice" },
	{ name: "Gastly", id: "gastly", type1: "Ghost", type2: "Poison" },
	{ name: "Haunter", id: "haunter", type1: "Ghost", type2: "Poison" },
	{ name: "Gengar", id: "gengar", type1: "Ghost", type2: "Poison" },
	{ name: "Mega Gengar", id: "mega gengar", type1: "Ghost", type2: "Poison" },
	{
		name: "Gigantamax Gengar",
		id: "gigantamax gengar",
		type1: "Ghost",
		type2: "Poison",
	},
	{ name: "Onix", id: "onix", type1: "Rock", type2: "Ground" },
	{ name: "Drowzee", id: "drowzee", type1: "Psychic", type2: "" },
	{ name: "Hypno", id: "hypno", type1: "Psychic", type2: "" },
	{ name: "Krabby", id: "krabby", type1: "Water", type2: "" },
	{ name: "Kingler", id: "kingler", type1: "Water", type2: "" },
	{
		name: "Gigantamax Kingler",
		id: "gigantamax kingler",
		type1: "Water",
		type2: "",
	},
	{ name: "Voltorb", id: "voltorb", type1: "Electric", type2: "" },
	{ name: "Electrode", id: "electrode", type1: "Electric", type2: "" },
	{ name: "Exeggcute", id: "exeggcute", type1: "Grass", type2: "Psychic" },
	{ name: "Exeggutor", id: "exeggutor", type1: "Grass", type2: "Psychic" },
	{
		name: "Alolan Exeggutor",
		id: "alolan exeggutor",
		type1: "Grass",
		type2: "Dragon",
	},
	{ name: "Cubone", id: "cubone", type1: "Ground", type2: "" },
	{ name: "Marowak", id: "marowak", type1: "Ground", type2: "" },
	{
		name: "Alolan Marowak",
		id: "alolan marowak",
		type1: "Fire",
		type2: "Ghost",
	},
	{ name: "Hitmonlee", id: "hitmonlee", type1: "Fighting", type2: "" },
	{ name: "Hitmonchan", id: "hitmonchan", type1: "Fighting", type2: "" },
	{ name: "Lickitung", id: "lickitung", type1: "Normal", type2: "" },
	{ name: "Koffing", id: "koffing", type1: "Poison", type2: "" },
	{ name: "Weezing", id: "weezing", type1: "Poison", type2: "" },
	{
		name: "Galarian Weezing",
		id: "galarian weezing",
		type1: "Poison",
		type2: "Fairy",
	},
	{ name: "Rhyhorn", id: "rhyhorn", type1: "Ground", type2: "Rock" },
	{ name: "Rhydon", id: "rhydon", type1: "Ground", type2: "Rock" },
	{ name: "Chansey", id: "chansey", type1: "Normal", type2: "" },
	{ name: "Tangela", id: "tangela", type1: "Grass", type2: "" },
	{ name: "Kangaskhan", id: "kangaskhan", type1: "Normal", type2: "" },
	{
		name: "Mega Kangaskhan",
		id: "mega kangaskhan",
		type1: "Normal",
		type2: "",
	},
	{ name: "Horsea", id: "horsea", type1: "Water", type2: "" },
	{ name: "Seadra", id: "seadra", type1: "Water", type2: "" },
	{ name: "Goldeen", id: "goldeen", type1: "Water", type2: "" },
	{ name: "Seaking", id: "seaking", type1: "Water", type2: "" },
	{ name: "Staryu", id: "staryu", type1: "Water", type2: "" },
	{ name: "Starmie", id: "starmie", type1: "Water", type2: "Psychic" },
	{ name: "Mr. Mime", id: "mr. mime", type1: "Psychic", type2: "Fairy" },
	{
		name: "Galarian Mr. Mime",
		id: "galarian mr. mime",
		type1: "Ice",
		type2: "Psychic",
	},
	{ name: "Scyther", id: "scyther", type1: "Bug", type2: "Flying" },
	{ name: "Jynx", id: "jynx", type1: "Ice", type2: "Psychic" },
	{ name: "Electabuzz", id: "electabuzz", type1: "Electric", type2: "" },
	{ name: "Magmar", id: "magmar", type1: "Fire", type2: "" },
	{ name: "Pinsir", id: "pinsir", type1: "Bug", type2: "" },
	{ name: "Mega Pinsir", id: "mega pinsir", type1: "Bug", type2: "Flying" },
	{ name: "Tauros", id: "tauros", type1: "Normal", type2: "" },
	{ name: "Magikarp", id: "magikarp", type1: "Water", type2: "" },
	{ name: "Gyarados", id: "gyarados", type1: "Water", type2: "Flying" },
	{
		name: "Mega Gyarados",
		id: "mega gyarados",
		type1: "Water",
		type2: "Flying",
	},
	{ name: "Lapras", id: "lapras", type1: "Water", type2: "Ice" },
	{
		name: "Gigantamax Lapras",
		id: "gigantamax lapras",
		type1: "Water",
		type2: "Ice",
	},
	{ name: "Ditto", id: "ditto", type1: "Normal", type2: "" },
	{ name: "Eevee", id: "eevee", type1: "Normal", type2: "" },
	{ name: "Eevee Partner", id: "eevee partner", type1: "Normal", type2: "" },
	{
		name: "Gigantamax Eevee",
		id: "gigantamax eevee",
		type1: "Normal",
		type2: "",
	},
	{ name: "Vaporeon", id: "vaporeon", type1: "Water", type2: "" },
	{ name: "Jolteon", id: "jolteon", type1: "Electric", type2: "" },
	{ name: "Flareon", id: "flareon", type1: "Fire", type2: "" },
	{ name: "Porygon", id: "porygon", type1: "Normal", type2: "" },
	{ name: "Omanyte", id: "omanyte", type1: "Rock", type2: "Water" },
	{ name: "Omastar", id: "omastar", type1: "Rock", type2: "Water" },
	{ name: "Kabuto", id: "kabuto", type1: "Rock", type2: "Water" },
	{ name: "Kabutops", id: "kabutops", type1: "Rock", type2: "Water" },
	{ name: "Aerodactyl", id: "aerodactyl", type1: "Rock", type2: "Flying" },
	{
		name: "Mega Aerodactyl",
		id: "mega aerodactyl",
		type1: "Rock",
		type2: "Flying",
	},
	{ name: "Snorlax", id: "snorlax", type1: "Normal", type2: "" },
	{
		name: "Gigantamax Snorlax",
		id: "gigantamax snorlax",
		type1: "Normal",
		type2: "",
	},
	{ name: "Articuno", id: "articuno", type1: "Ice", type2: "Flying" },
	{
		name: "Galarian Articuno",
		id: "galarian articuno",
		type1: "Psychic",
		type2: "Flying",
	},
	{ name: "Zapdos", id: "zapdos", type1: "Electric", type2: "Flying" },
	{
		name: "Galarian Zapdos",
		id: "galarian zapdos",
		type1: "Fighting",
		type2: "Flying",
	},
	{ name: "Moltres", id: "moltres", type1: "Fire", type2: "Flying" },
	{
		name: "Galarian Moltres",
		id: "galarian moltres",
		type1: "Dark",
		type2: "Flying",
	},
	{ name: "Dratini", id: "dratini", type1: "Dragon", type2: "" },
	{ name: "Dragonair", id: "dragonair", type1: "Dragon", type2: "" },
	{ name: "Dragonite", id: "dragonite", type1: "Dragon", type2: "Flying" },
	{ name: "Mewtwo", id: "mewtwo", type1: "Psychic", type2: "" },
	{
		name: "Mega Mewtwo X",
		id: "mega mewtwo x",
		type1: "Psychic",
		type2: "Fighting",
	},
	{ name: "Mega Mewtwo Y", id: "mega mewtwo y", type1: "Psychic", type2: "" },
	{ name: "Shadow Mewtwo", id: "shadow mewtwo", type1: "", type2: "" },
	{ name: "Mew", id: "mew", type1: "Psychic", type2: "" },
	{ name: "Chikorita", id: "chikorita", type1: "Grass", type2: "" },
	{ name: "Bayleef", id: "bayleef", type1: "Grass", type2: "" },
	{ name: "Meganium", id: "meganium", type1: "Grass", type2: "" },
	{ name: "Cyndaquil", id: "cyndaquil", type1: "Fire", type2: "" },
	{ name: "Quilava", id: "quilava", type1: "Fire", type2: "" },
	{ name: "Typhlosion", id: "typhlosion", type1: "Fire", type2: "" },
	{ name: "Totodile", id: "totodile", type1: "Water", type2: "" },
	{ name: "Croconaw", id: "croconaw", type1: "Water", type2: "" },
	{ name: "Feraligatr", id: "feraligatr", type1: "Water", type2: "" },
	{ name: "Sentret", id: "sentret", type1: "Normal", type2: "" },
	{ name: "Furret", id: "furret", type1: "Normal", type2: "" },
	{ name: "Hoothoot", id: "hoothoot", type1: "Normal", type2: "Flying" },
	{ name: "Noctowl", id: "noctowl", type1: "Normal", type2: "Flying" },
	{ name: "Ledyba", id: "ledyba", type1: "Bug", type2: "Flying" },
	{ name: "Ledian", id: "ledian", type1: "Bug", type2: "Flying" },
	{ name: "Spinarak", id: "spinarak", type1: "Bug", type2: "Poison" },
	{ name: "Ariados", id: "ariados", type1: "Bug", type2: "Poison" },
	{ name: "Crobat", id: "crobat", type1: "Poison", type2: "Flying" },
	{ name: "Chinchou", id: "chinchou", type1: "Water", type2: "Electric" },
	{ name: "Lanturn", id: "lanturn", type1: "Water", type2: "Electric" },
	{ name: "Pichu", id: "pichu", type1: "Electric", type2: "" },
	{ name: "Cleffa", id: "cleffa", type1: "Fairy", type2: "" },
	{ name: "Igglybuff", id: "igglybuff", type1: "Normal", type2: "Fairy" },
	{ name: "Togepi", id: "togepi", type1: "Fairy", type2: "" },
	{ name: "Togetic", id: "togetic", type1: "Fairy", type2: "Flying" },
	{ name: "Natu", id: "natu", type1: "Psychic", type2: "Flying" },
	{ name: "Xatu", id: "xatu", type1: "Psychic", type2: "Flying" },
	{ name: "Mareep", id: "mareep", type1: "Electric", type2: "" },
	{ name: "Flaaffy", id: "flaaffy", type1: "Electric", type2: "" },
	{ name: "Ampharos", id: "ampharos", type1: "Electric", type2: "" },
	{
		name: "Mega Ampharos",
		id: "mega ampharos",
		type1: "Electric",
		type2: "Dragon",
	},
	{ name: "Bellossom", id: "bellossom", type1: "Grass", type2: "" },
	{ name: "Marill", id: "marill", type1: "Water", type2: "Fairy" },
	{ name: "Azumarill", id: "azumarill", type1: "Water", type2: "Fairy" },
	{ name: "Sudowoodo", id: "sudowoodo", type1: "Rock", type2: "" },
	{ name: "Politoed", id: "politoed", type1: "Water", type2: "" },
	{ name: "Hoppip", id: "hoppip", type1: "Grass", type2: "Flying" },
	{ name: "Skiploom", id: "skiploom", type1: "Grass", type2: "Flying" },
	{ name: "Jumpluff", id: "jumpluff", type1: "Grass", type2: "Flying" },
	{ name: "Aipom", id: "aipom", type1: "Normal", type2: "" },
	{ name: "Sunkern", id: "sunkern", type1: "Grass", type2: "" },
	{ name: "Sunflora", id: "sunflora", type1: "Grass", type2: "" },
	{ name: "Yanma", id: "yanma", type1: "Bug", type2: "Flying" },
	{ name: "Wooper", id: "wooper", type1: "Water", type2: "Ground" },
	{ name: "Quagsire", id: "quagsire", type1: "Water", type2: "Ground" },
	{ name: "Espeon", id: "espeon", type1: "Psychic", type2: "" },
	{ name: "Umbreon", id: "umbreon", type1: "Dark", type2: "" },
	{ name: "Murkrow", id: "murkrow", type1: "Dark", type2: "Flying" },
	{ name: "Slowking", id: "slowking", type1: "Water", type2: "Psychic" },
	{
		name: "Galarian Slowking",
		id: "galarian slowking",
		type1: "TBA",
		type2: "TBA",
	},
	{ name: "Misdreavus", id: "misdreavus", type1: "Ghost", type2: "" },
	{ name: "Unown", id: "unown", type1: "Psychic", type2: "" },
	{ name: "Wobbuffet", id: "wobbuffet", type1: "Psychic", type2: "" },
	{ name: "Girafarig", id: "girafarig", type1: "Normal", type2: "Psychic" },
	{ name: "Pineco", id: "pineco", type1: "Bug", type2: "" },
	{ name: "Forretress", id: "forretress", type1: "Bug", type2: "Steel" },
	{ name: "Dunsparce", id: "dunsparce", type1: "Normal", type2: "" },
	{ name: "Gligar", id: "gligar", type1: "Ground", type2: "Flying" },
	{ name: "Steelix", id: "steelix", type1: "Steel", type2: "Ground" },
	{ name: "Mega Steelix", id: "mega steelix", type1: "Steel", type2: "Ground" },
	{ name: "Snubbull", id: "snubbull", type1: "Fairy", type2: "" },
	{ name: "Granbull", id: "granbull", type1: "Fairy", type2: "" },
	{ name: "Qwilfish", id: "qwilfish", type1: "Water", type2: "Poison" },
	{ name: "Scizor", id: "scizor", type1: "Bug", type2: "Steel" },
	{ name: "Mega Scizor", id: "mega scizor", type1: "Bug", type2: "Steel" },
	{ name: "Shuckle", id: "shuckle", type1: "Bug", type2: "Rock" },
	{ name: "Heracross", id: "heracross", type1: "Bug", type2: "Fighting" },
	{
		name: "Mega Heracross",
		id: "mega heracross",
		type1: "Bug",
		type2: "Fighting",
	},
	{ name: "Sneasel", id: "sneasel", type1: "Dark", type2: "Ice" },
	{ name: "Teddiursa", id: "teddiursa", type1: "Normal", type2: "" },
	{ name: "Ursaring", id: "ursaring", type1: "Normal", type2: "" },
	{ name: "Slugma", id: "slugma", type1: "Fire", type2: "" },
	{ name: "Magcargo", id: "magcargo", type1: "Fire", type2: "Rock" },
	{ name: "Swinub", id: "swinub", type1: "Ice", type2: "Ground" },
	{ name: "Piloswine", id: "piloswine", type1: "Ice", type2: "Ground" },
	{ name: "Corsola", id: "corsola", type1: "Water", type2: "Rock" },
	{
		name: "Galarian Corsola",
		id: "galarian corsola",
		type1: "Ghost",
		type2: "",
	},
	{ name: "Remoraid", id: "remoraid", type1: "Water", type2: "" },
	{ name: "Octillery", id: "octillery", type1: "Water", type2: "" },
	{ name: "Delibird", id: "delibird", type1: "Ice", type2: "Flying" },
	{ name: "Mantine", id: "mantine", type1: "Water", type2: "Flying" },
	{ name: "Skarmory", id: "skarmory", type1: "Steel", type2: "Flying" },
	{ name: "Houndour", id: "houndour", type1: "Dark", type2: "Fire" },
	{ name: "Houndoom", id: "houndoom", type1: "Dark", type2: "Fire" },
	{ name: "Mega Houndoom", id: "mega houndoom", type1: "Dark", type2: "Fire" },
	{ name: "Kingdra", id: "kingdra", type1: "Water", type2: "Dragon" },
	{ name: "Phanpy", id: "phanpy", type1: "Ground", type2: "" },
	{ name: "Donphan", id: "donphan", type1: "Ground", type2: "" },
	{ name: "Porygon2", id: "porygon2", type1: "Normal", type2: "" },
	{ name: "Stantler", id: "stantler", type1: "Normal", type2: "" },
	{ name: "Smeargle", id: "smeargle", type1: "Normal", type2: "" },
	{ name: "Tyrogue", id: "tyrogue", type1: "Fighting", type2: "" },
	{ name: "Hitmontop", id: "hitmontop", type1: "Fighting", type2: "" },
	{ name: "Smoochum", id: "smoochum", type1: "Ice", type2: "Psychic" },
	{ name: "Elekid", id: "elekid", type1: "Electric", type2: "" },
	{ name: "Magby", id: "magby", type1: "Fire", type2: "" },
	{ name: "Miltank", id: "miltank", type1: "Normal", type2: "" },
	{ name: "Blissey", id: "blissey", type1: "Normal", type2: "" },
	{ name: "Raikou", id: "raikou", type1: "Electric", type2: "" },
	{ name: "Entei", id: "entei", type1: "Fire", type2: "" },
	{ name: "Suicune", id: "suicune", type1: "Water", type2: "" },
	{ name: "Larvitar", id: "larvitar", type1: "Rock", type2: "Ground" },
	{ name: "Pupitar", id: "pupitar", type1: "Rock", type2: "Ground" },
	{ name: "Tyranitar", id: "tyranitar", type1: "Rock", type2: "Dark" },
	{
		name: "Mega Tyranitar",
		id: "mega tyranitar",
		type1: "Rock",
		type2: "Dark",
	},
	{ name: "Lugia", id: "lugia", type1: "Psychic", type2: "Flying" },
	{ name: "Shadow Lugia", id: "shadow lugia", type1: "", type2: "" },
	{ name: "Ho-Oh", id: "ho-oh", type1: "Fire", type2: "Flying" },
	{ name: "Celebi", id: "celebi", type1: "Psychic", type2: "Grass" },
	{ name: "Treecko", id: "treecko", type1: "Grass", type2: "" },
	{ name: "Grovyle", id: "grovyle", type1: "Grass", type2: "" },
	{ name: "Sceptile", id: "sceptile", type1: "Grass", type2: "" },
	{
		name: "Mega Sceptile",
		id: "mega sceptile",
		type1: "Grass",
		type2: "Dragon",
	},
	{ name: "Torchic", id: "torchic", type1: "Fire", type2: "" },
	{ name: "Combusken", id: "combusken", type1: "Fire", type2: "Fighting" },
	{ name: "Blaziken", id: "blaziken", type1: "Fire", type2: "Fighting" },
	{
		name: "Mega Blaziken",
		id: "mega blaziken",
		type1: "Fire",
		type2: "Fighting",
	},
	{ name: "Mudkip", id: "mudkip", type1: "Water", type2: "" },
	{ name: "Marshtomp", id: "marshtomp", type1: "Water", type2: "Ground" },
	{ name: "Swampert", id: "swampert", type1: "Water", type2: "Ground" },
	{
		name: "Mega Swampert",
		id: "mega swampert",
		type1: "Water",
		type2: "Ground",
	},
	{ name: "Poochyena", id: "poochyena", type1: "Dark", type2: "" },
	{ name: "Mightyena", id: "mightyena", type1: "Dark", type2: "" },
	{ name: "Zigzagoon", id: "zigzagoon", type1: "Normal", type2: "" },
	{
		name: "Galarian Zigzagoon",
		id: "galarian zigzagoon",
		type1: "Dark",
		type2: "Normal",
	},
	{ name: "Linoone", id: "linoone", type1: "Normal", type2: "" },
	{
		name: "Galarian Linoone",
		id: "galarian linoone",
		type1: "Dark",
		type2: "Normal",
	},
	{ name: "Wurmple", id: "wurmple", type1: "Bug", type2: "" },
	{ name: "Silcoon", id: "silcoon", type1: "Bug", type2: "" },
	{ name: "Beautifly", id: "beautifly", type1: "Bug", type2: "Flying" },
	{ name: "Cascoon", id: "cascoon", type1: "Bug", type2: "" },
	{ name: "Dustox", id: "dustox", type1: "Bug", type2: "Poison" },
	{ name: "Lotad", id: "lotad", type1: "Water", type2: "Grass" },
	{ name: "Lombre", id: "lombre", type1: "Water", type2: "Grass" },
	{ name: "Ludicolo", id: "ludicolo", type1: "Water", type2: "Grass" },
	{ name: "Seedot", id: "seedot", type1: "Grass", type2: "" },
	{ name: "Nuzleaf", id: "nuzleaf", type1: "Grass", type2: "Dark" },
	{ name: "Shiftry", id: "shiftry", type1: "Grass", type2: "Dark" },
	{ name: "Taillow", id: "taillow", type1: "Normal", type2: "Flying" },
	{ name: "Swellow", id: "swellow", type1: "Normal", type2: "Flying" },
	{ name: "Wingull", id: "wingull", type1: "Water", type2: "Flying" },
	{ name: "Pelipper", id: "pelipper", type1: "Water", type2: "Flying" },
	{ name: "Ralts", id: "ralts", type1: "Psychic", type2: "Fairy" },
	{ name: "Kirlia", id: "kirlia", type1: "Psychic", type2: "Fairy" },
	{ name: "Gardevoir", id: "gardevoir", type1: "Psychic", type2: "Fairy" },
	{
		name: "Mega Gardevoir",
		id: "mega gardevoir",
		type1: "Psychic",
		type2: "Fairy",
	},
	{ name: "Surskit", id: "surskit", type1: "Bug", type2: "Water" },
	{ name: "Masquerain", id: "masquerain", type1: "Bug", type2: "Flying" },
	{ name: "Shroomish", id: "shroomish", type1: "Grass", type2: "" },
	{ name: "Breloom", id: "breloom", type1: "Grass", type2: "Fighting" },
	{ name: "Slakoth", id: "slakoth", type1: "Normal", type2: "" },
	{ name: "Vigoroth", id: "vigoroth", type1: "Normal", type2: "" },
	{ name: "Slaking", id: "slaking", type1: "Normal", type2: "" },
	{ name: "Nincada", id: "nincada", type1: "Bug", type2: "Ground" },
	{ name: "Ninjask", id: "ninjask", type1: "Bug", type2: "Flying" },
	{ name: "Shedinja", id: "shedinja", type1: "Bug", type2: "Ghost" },
	{ name: "Whismur", id: "whismur", type1: "Normal", type2: "" },
	{ name: "Loudred", id: "loudred", type1: "Normal", type2: "" },
	{ name: "Exploud", id: "exploud", type1: "Normal", type2: "" },
	{ name: "Makuhita", id: "makuhita", type1: "Fighting", type2: "" },
	{ name: "Hariyama", id: "hariyama", type1: "Fighting", type2: "" },
	{ name: "Azurill", id: "azurill", type1: "Normal", type2: "Fairy" },
	{ name: "Nosepass", id: "nosepass", type1: "Rock", type2: "" },
	{ name: "Skitty", id: "skitty", type1: "Normal", type2: "" },
	{ name: "Delcatty", id: "delcatty", type1: "Normal", type2: "" },
	{ name: "Sableye", id: "sableye", type1: "Dark", type2: "Ghost" },
	{ name: "Mega Sableye", id: "mega sableye", type1: "Dark", type2: "Ghost" },
	{ name: "Mawile", id: "mawile", type1: "Steel", type2: "Fairy" },
	{ name: "Mega Mawile", id: "mega mawile", type1: "Steel", type2: "Fairy" },
	{ name: "Aron", id: "aron", type1: "Steel", type2: "Rock" },
	{ name: "Lairon", id: "lairon", type1: "Steel", type2: "Rock" },
	{ name: "Aggron", id: "aggron", type1: "Steel", type2: "Rock" },
	{ name: "Mega Aggron", id: "mega aggron", type1: "Steel", type2: "" },
	{ name: "Meditite", id: "meditite", type1: "Fighting", type2: "Psychic" },
	{ name: "Medicham", id: "medicham", type1: "Fighting", type2: "Psychic" },
	{
		name: "Mega Medicham",
		id: "mega medicham",
		type1: "Fighting",
		type2: "Psychic",
	},
	{ name: "Electrike", id: "electrike", type1: "Electric", type2: "" },
	{ name: "Manectric", id: "manectric", type1: "Electric", type2: "" },
	{
		name: "Mega Manectric",
		id: "mega manectric",
		type1: "Electric",
		type2: "",
	},
	{ name: "Plusle", id: "plusle", type1: "Electric", type2: "" },
	{ name: "Minun", id: "minun", type1: "Electric", type2: "" },
	{ name: "Volbeat", id: "volbeat", type1: "Bug", type2: "" },
	{ name: "Illumise", id: "illumise", type1: "Bug", type2: "" },
	{ name: "Roselia", id: "roselia", type1: "Grass", type2: "Poison" },
	{ name: "Gulpin", id: "gulpin", type1: "Poison", type2: "" },
	{ name: "Swalot", id: "swalot", type1: "Poison", type2: "" },
	{ name: "Carvanha", id: "carvanha", type1: "Water", type2: "Dark" },
	{ name: "Sharpedo", id: "sharpedo", type1: "Water", type2: "Dark" },
	{ name: "Mega Sharpedo", id: "mega sharpedo", type1: "Water", type2: "Dark" },
	{ name: "Wailmer", id: "wailmer", type1: "Water", type2: "" },
	{ name: "Wailord", id: "wailord", type1: "Water", type2: "" },
	{ name: "Numel", id: "numel", type1: "Fire", type2: "Ground" },
	{ name: "Camerupt", id: "camerupt", type1: "Fire", type2: "Ground" },
	{
		name: "Mega Camerupt",
		id: "mega camerupt",
		type1: "Fire",
		type2: "Ground",
	},
	{ name: "Torkoal", id: "torkoal", type1: "Fire", type2: "" },
	{ name: "Spoink", id: "spoink", type1: "Psychic", type2: "" },
	{ name: "Grumpig", id: "grumpig", type1: "Psychic", type2: "" },
	{ name: "Spinda", id: "spinda", type1: "Normal", type2: "" },
	{ name: "Trapinch", id: "trapinch", type1: "Ground", type2: "" },
	{ name: "Vibrava", id: "vibrava", type1: "Ground", type2: "Dragon" },
	{ name: "Flygon", id: "flygon", type1: "Ground", type2: "Dragon" },
	{ name: "Cacnea", id: "cacnea", type1: "Grass", type2: "" },
	{ name: "Cacturne", id: "cacturne", type1: "Grass", type2: "Dark" },
	{ name: "Swablu", id: "swablu", type1: "Normal", type2: "Flying" },
	{ name: "Altaria", id: "altaria", type1: "Dragon", type2: "Flying" },
	{ name: "Mega Altaria", id: "mega altaria", type1: "Dragon", type2: "Fairy" },
	{ name: "Zangoose", id: "zangoose", type1: "Normal", type2: "" },
	{ name: "Seviper", id: "seviper", type1: "Poison", type2: "" },
	{ name: "Lunatone", id: "lunatone", type1: "Rock", type2: "Psychic" },
	{ name: "Solrock", id: "solrock", type1: "Rock", type2: "Psychic" },
	{ name: "Barboach", id: "barboach", type1: "Water", type2: "Ground" },
	{ name: "Whiscash", id: "whiscash", type1: "Water", type2: "Ground" },
	{ name: "Corphish", id: "corphish", type1: "Water", type2: "" },
	{ name: "Crawdaunt", id: "crawdaunt", type1: "Water", type2: "Dark" },
	{ name: "Baltoy", id: "baltoy", type1: "Ground", type2: "Psychic" },
	{ name: "Claydol", id: "claydol", type1: "Ground", type2: "Psychic" },
	{ name: "Lileep", id: "lileep", type1: "Rock", type2: "Grass" },
	{ name: "Cradily", id: "cradily", type1: "Rock", type2: "Grass" },
	{ name: "Anorith", id: "anorith", type1: "Rock", type2: "Bug" },
	{ name: "Armaldo", id: "armaldo", type1: "Rock", type2: "Bug" },
	{ name: "Feebas", id: "feebas", type1: "Water", type2: "" },
	{ name: "Milotic", id: "milotic", type1: "Water", type2: "" },
	{ name: "Castform", id: "castform", type1: "Normal", type2: "" },
	{ name: "Castform Sunny", id: "castform sunny", type1: "Fire", type2: "" },
	{ name: "Castform Rainy", id: "castform rainy", type1: "Water", type2: "" },
	{ name: "Castform Snowy", id: "castform snowy", type1: "Ice", type2: "" },
	{ name: "Kecleon", id: "kecleon", type1: "Normal", type2: "" },
	{ name: "Shuppet", id: "shuppet", type1: "Ghost", type2: "" },
	{ name: "Banette", id: "banette", type1: "Ghost", type2: "" },
	{ name: "Mega Banette", id: "mega banette", type1: "", type2: "" },
	{ name: "Duskull", id: "duskull", type1: "Ghost", type2: "" },
	{ name: "Dusclops", id: "dusclops", type1: "Ghost", type2: "" },
	{ name: "Tropius", id: "tropius", type1: "Grass", type2: "Flying" },
	{ name: "Chimecho", id: "chimecho", type1: "Psychic", type2: "" },
	{ name: "Absol", id: "absol", type1: "Dark", type2: "" },
	{ name: "Mega Absol", id: "mega absol", type1: "Dark", type2: "" },
	{ name: "Wynaut", id: "wynaut", type1: "Psychic", type2: "" },
	{ name: "Snorunt", id: "snorunt", type1: "Ice", type2: "" },
	{ name: "Glalie", id: "glalie", type1: "Ice", type2: "" },
	{ name: "Mega Glalie", id: "mega glalie", type1: "Ice", type2: "" },
	{ name: "Spheal", id: "spheal", type1: "Ice", type2: "Water" },
	{ name: "Sealeo", id: "sealeo", type1: "Ice", type2: "Water" },
	{ name: "Walrein", id: "walrein", type1: "Ice", type2: "Water" },
	{ name: "Clamperl", id: "clamperl", type1: "Water", type2: "" },
	{ name: "Huntail", id: "huntail", type1: "Water", type2: "" },
	{ name: "Gorebyss", id: "gorebyss", type1: "Water", type2: "" },
	{ name: "Relicanth", id: "relicanth", type1: "Water", type2: "Rock" },
	{ name: "Luvdisc", id: "luvdisc", type1: "Water", type2: "" },
	{ name: "Bagon", id: "bagon", type1: "Dragon", type2: "" },
	{ name: "Shelgon", id: "shelgon", type1: "Dragon", type2: "" },
	{ name: "Salamence", id: "salamence", type1: "Dragon", type2: "Flying" },
	{
		name: "Mega Salamence",
		id: "mega salamence",
		type1: "Dragon",
		type2: "Flying",
	},
	{ name: "Beldum", id: "beldum", type1: "Steel", type2: "Psychic" },
	{ name: "Metang", id: "metang", type1: "Steel", type2: "Psychic" },
	{ name: "Metagross", id: "metagross", type1: "Steel", type2: "Psychic" },
	{
		name: "Mega Metagross",
		id: "mega metagross",
		type1: "Steel",
		type2: "Psychic",
	},
	{ name: "Regirock", id: "regirock", type1: "Rock", type2: "" },
	{ name: "Regice", id: "regice", type1: "Ice", type2: "" },
	{ name: "Registeel", id: "registeel", type1: "Steel", type2: "" },
	{ name: "Latias", id: "latias", type1: "Dragon", type2: "Psychic" },
	{ name: "Mega Latias", id: "mega latias", type1: "Dragon", type2: "Psychic" },
	{ name: "Latios", id: "latios", type1: "Dragon", type2: "Psychic" },
	{ name: "Mega Latios", id: "mega latios", type1: "Dragon", type2: "Psychic" },
	{ name: "Kyogre", id: "kyogre", type1: "Water", type2: "" },
	{ name: "Primal Kyogre", id: "primal kyogre", type1: "Water", type2: "" },
	{ name: "Groudon", id: "groudon", type1: "Ground", type2: "" },
	{
		name: "Primal Groudon",
		id: "primal groudon",
		type1: "Ground",
		type2: "Fire",
	},
	{ name: "Rayquaza", id: "rayquaza", type1: "Dragon", type2: "Flying" },
	{
		name: "Mega Rayquaza",
		id: "mega rayquaza",
		type1: "Dragon",
		type2: "Flying",
	},
	{ name: "Jirachi", id: "jirachi", type1: "Steel", type2: "Psychic" },
	{ name: "Deoxys", id: "deoxys", type1: "Psychic", type2: "" },
	{ name: "Deoxys Attack", id: "deoxys attack", type1: "Psychic", type2: "" },
	{ name: "Deoxys Defense", id: "deoxys defense", type1: "Psychic", type2: "" },
	{ name: "Deoxys Speed", id: "deoxys speed", type1: "Psychic", type2: "" },
	{ name: "Turtwig", id: "turtwig", type1: "Grass", type2: "" },
	{ name: "Grotle", id: "grotle", type1: "Grass", type2: "" },
	{ name: "Torterra", id: "torterra", type1: "Grass", type2: "Ground" },
	{ name: "Chimchar", id: "chimchar", type1: "Fire", type2: "" },
	{ name: "Monferno", id: "monferno", type1: "Fire", type2: "Fighting" },
	{ name: "Infernape", id: "infernape", type1: "Fire", type2: "Fighting" },
	{ name: "Piplup", id: "piplup", type1: "Water", type2: "" },
	{ name: "Prinplup", id: "prinplup", type1: "Water", type2: "" },
	{ name: "Empoleon", id: "empoleon", type1: "Water", type2: "Steel" },
	{ name: "Starly", id: "starly", type1: "Normal", type2: "Flying" },
	{ name: "Staravia", id: "staravia", type1: "Normal", type2: "Flying" },
	{ name: "Staraptor", id: "staraptor", type1: "Normal", type2: "Flying" },
	{ name: "Bidoof", id: "bidoof", type1: "Normal", type2: "" },
	{ name: "Bibarel", id: "bibarel", type1: "Normal", type2: "Water" },
	{ name: "Kricketot", id: "kricketot", type1: "Bug", type2: "" },
	{ name: "Kricketune", id: "kricketune", type1: "Bug", type2: "" },
	{ name: "Shinx", id: "shinx", type1: "Electric", type2: "" },
	{ name: "Luxio", id: "luxio", type1: "Electric", type2: "" },
	{ name: "Luxray", id: "luxray", type1: "Electric", type2: "" },
	{ name: "Budew", id: "budew", type1: "Grass", type2: "Poison" },
	{ name: "Roserade", id: "roserade", type1: "Grass", type2: "Poison" },
	{ name: "Cranidos", id: "cranidos", type1: "Rock", type2: "" },
	{ name: "Rampardos", id: "rampardos", type1: "Rock", type2: "" },
	{ name: "Shieldon", id: "shieldon", type1: "Rock", type2: "Steel" },
	{ name: "Bastiodon", id: "bastiodon", type1: "Rock", type2: "Steel" },
	{
		name: "Burmy Plant Cloak",
		id: "burmy plant cloak",
		type1: "Bug",
		type2: "",
	},
	{
		name: "Burmy Sandy Cloak",
		id: "burmy sandy cloak",
		type1: "Bug",
		type2: "",
	},
	{
		name: "Burmy Trash Cloak",
		id: "burmy trash cloak",
		type1: "Bug",
		type2: "",
	},
	{
		name: "Wormadam Plant Cloak",
		id: "wormadam plant cloak",
		type1: "Bug",
		type2: "Grass",
	},
	{
		name: "Wormadam Sandy Cloak",
		id: "wormadam sandy cloak",
		type1: "Bug",
		type2: "Ground",
	},
	{
		name: "Wormadam Trash Cloak",
		id: "wormadam trash cloak",
		type1: "Bug",
		type2: "Steel",
	},
	{ name: "Mothim", id: "mothim", type1: "Bug", type2: "Flying" },
	{ name: "Combee", id: "combee", type1: "Bug", type2: "Flying" },
	{ name: "Vespiquen", id: "vespiquen", type1: "Bug", type2: "Flying" },
	{ name: "Pachirisu", id: "pachirisu", type1: "Electric", type2: "" },
	{ name: "Buizel", id: "buizel", type1: "Water", type2: "" },
	{ name: "Floatzel", id: "floatzel", type1: "Water", type2: "" },
	{ name: "Cherubi", id: "cherubi", type1: "Grass", type2: "" },
	{
		name: "Cherrim Overcast",
		id: "cherrim overcast",
		type1: "Grass",
		type2: "",
	},
	{
		name: "Cherrim Sunshine",
		id: "cherrim sunshine",
		type1: "Grass",
		type2: "",
	},
	{
		name: "Shellos West Sea",
		id: "shellos west sea",
		type1: "Water",
		type2: "",
	},
	{
		name: "Shellos East Sea",
		id: "shellos east sea",
		type1: "Water",
		type2: "",
	},
	{
		name: "Gastrodon West Sea",
		id: "gastrodon west sea",
		type1: "Water",
		type2: "Ground",
	},
	{
		name: "Gastrodon East Sea",
		id: "gastrodon east sea",
		type1: "Water",
		type2: "Ground",
	},
	{ name: "Ambipom", id: "ambipom", type1: "Normal", type2: "" },
	{ name: "Drifloon", id: "drifloon", type1: "Ghost", type2: "Flying" },
	{ name: "Drifblim", id: "drifblim", type1: "Ghost", type2: "Flying" },
	{ name: "Buneary", id: "buneary", type1: "Normal", type2: "" },
	{ name: "Lopunny", id: "lopunny", type1: "Normal", type2: "" },
	{
		name: "Mega Lopunny",
		id: "mega lopunny",
		type1: "Normal",
		type2: "Fighting",
	},
	{ name: "Mismagius", id: "mismagius", type1: "Ghost", type2: "" },
	{ name: "Honchkrow", id: "honchkrow", type1: "Dark", type2: "Flying" },
	{ name: "Glameow", id: "glameow", type1: "Normal", type2: "" },
	{ name: "Purugly", id: "purugly", type1: "Normal", type2: "" },
	{ name: "Chingling", id: "chingling", type1: "Psychic", type2: "" },
	{ name: "Stunky", id: "stunky", type1: "Poison", type2: "Dark" },
	{ name: "Skuntank", id: "skuntank", type1: "Poison", type2: "Dark" },
	{ name: "Bronzor", id: "bronzor", type1: "Steel", type2: "Psychic" },
	{ name: "Bronzong", id: "bronzong", type1: "Steel", type2: "Psychic" },
	{ name: "Bonsly", id: "bonsly", type1: "Rock", type2: "" },
	{ name: "Mime Jr.", id: "mime jr.", type1: "Psychic", type2: "Fairy" },
	{ name: "Happiny", id: "happiny", type1: "Normal", type2: "" },
	{ name: "Chatot", id: "chatot", type1: "Normal", type2: "Flying" },
	{ name: "Spiritomb", id: "spiritomb", type1: "Ghost", type2: "Dark" },
	{ name: "Gible", id: "gible", type1: "Dragon", type2: "Ground" },
	{ name: "Gabite", id: "gabite", type1: "Dragon", type2: "Ground" },
	{ name: "Garchomp", id: "garchomp", type1: "Dragon", type2: "Ground" },
	{
		name: "Mega Garchomp",
		id: "mega garchomp",
		type1: "Dragon",
		type2: "Ground",
	},
	{ name: "Munchlax", id: "munchlax", type1: "Normal", type2: "" },
	{ name: "Riolu", id: "riolu", type1: "Fighting", type2: "" },
	{ name: "Lucario", id: "lucario", type1: "Fighting", type2: "Steel" },
	{
		name: "Mega Lucario",
		id: "mega lucario",
		type1: "Fighting",
		type2: "Steel",
	},
	{ name: "Hippopotas", id: "hippopotas", type1: "Ground", type2: "" },
	{ name: "Hippowdon", id: "hippowdon", type1: "Groud", type2: "" },
	{ name: "Skorupi", id: "skorupi", type1: "Poison", type2: "Bug" },
	{ name: "Drapion", id: "drapion", type1: "Poison", type2: "Dark" },
	{ name: "Croagunk", id: "croagunk", type1: "Poison", type2: "Fighting" },
	{ name: "Toxicroak", id: "toxicroak", type1: "Poison", type2: "Fighting" },
	{ name: "Carnivine", id: "carnivine", type1: "Grass", type2: "" },
	{ name: "Finneon", id: "finneon", type1: "Water", type2: "" },
	{ name: "Lumineon", id: "lumineon", type1: "Water", type2: "" },
	{ name: "Mantyke", id: "mantyke", type1: "Water", type2: "Flying" },
	{ name: "Snover", id: "snover", type1: "Grass", type2: "Ice" },
	{ name: "Abomasnow", id: "abomasnow", type1: "Grass", type2: "Ice" },
	{
		name: "Mega Abomasnow",
		id: "mega abomasnow",
		type1: "Grass",
		type2: "Ice",
	},
	{ name: "Weavile", id: "weavile", type1: "Dark", type2: "Ice" },
	{ name: "Magnezone", id: "magnezone", type1: "Electric", type2: "Steel" },
	{ name: "Lickilicky", id: "lickilicky", type1: "Normal", type2: "" },
	{ name: "Rhyperior", id: "rhyperior", type1: "Ground", type2: "Rock" },
	{ name: "Tangrowth", id: "tangrowth", type1: "Grass", type2: "" },
	{ name: "Electivire", id: "electivire", type1: "Electric", type2: "" },
	{ name: "Magmortar", id: "magmortar", type1: "Fire", type2: "" },
	{ name: "Togekiss", id: "togekiss", type1: "Fairy", type2: "Flying" },
	{ name: "Yanmega", id: "yanmega", type1: "Bug", type2: "Flying" },
	{ name: "Leafeon", id: "leafeon", type1: "Grass", type2: "" },
	{ name: "Glaceon", id: "glaceon", type1: "Ice", type2: "" },
	{ name: "Gliscor", id: "gliscor", type1: "Ground", type2: "Flying" },
	{ name: "Mamoswine", id: "mamoswine", type1: "Ice", type2: "Ground" },
	{ name: "Porygon-Z", id: "porygon-z", type1: "Normal", type2: "" },
	{ name: "Gallade", id: "gallade", type1: "Psychic", type2: "Fighting" },
	{
		name: "Mega Gallade",
		id: "mega gallade",
		type1: "Psychic",
		type2: "Fighting",
	},
	{ name: "Probopass", id: "probopass", type1: "Rock", type2: "Steel" },
	{ name: "Dusknoir", id: "dusknoir", type1: "Ghost", type2: "" },
	{ name: "Froslass", id: "froslass", type1: "Ice", type2: "Ghost" },
	{ name: "Rotom", id: "rotom", type1: "Electric", type2: "Ghost" },
	{ name: "Rotom Heat", id: "rotom heat", type1: "Electric", type2: "Fire" },
	{ name: "Rotom Wash", id: "rotom wash", type1: "Electric", type2: "Water" },
	{ name: "Rotom Frost", id: "rotom frost", type1: "Electric", type2: "Ice" },
	{ name: "Rotom Fan", id: "rotom fan", type1: "Electric", type2: "Flying" },
	{ name: "Rotom Mow", id: "rotom mow", type1: "Electric", type2: "Grass" },
	{ name: "Uxie", id: "uxie", type1: "Psychic", type2: "" },
	{ name: "Mesprit", id: "mesprit", type1: "Psychic", type2: "" },
	{ name: "Azelf", id: "azelf", type1: "Psychic", type2: "" },
	{ name: "Dialga", id: "dialga", type1: "Steel", type2: "Dragon" },
	{
		name: "Primal Dialga",
		id: "primal dialga",
		type1: "Steel",
		type2: "Dragon",
	},
	{ name: "Palkia", id: "palkia", type1: "Water", type2: "Dragon" },
	{ name: "Heatran", id: "heatran", type1: "Fire", type2: "Steel" },
	{ name: "Regigigas", id: "regigigas", type1: "Normal", type2: "" },
	{
		name: "Giratina Altered",
		id: "giratina altered",
		type1: "Ghost",
		type2: "Dragon",
	},
	{ name: "Giratina", id: "giratina", type1: "Ghost", type2: "Dragon" },
	{
		name: "Giratina Origin",
		id: "giratina origin",
		type1: "Ghost",
		type2: "Dragon",
	},
	{ name: "Cresselia", id: "cresselia", type1: "Psychic", type2: "" },
	{ name: "Phione", id: "phione", type1: "Water", type2: "" },
	{ name: "Manaphy", id: "manaphy", type1: "Water", type2: "" },
	{ name: "Darkrai", id: "darkrai", type1: "Dark", type2: "" },
	{ name: "Shaymin Land", id: "shaymin land", type1: "Grass", type2: "" },
	{ name: "Shaymin", id: "shaymin", type1: "Grass", type2: "" },
	{ name: "Shaymin Sky", id: "shaymin sky", type1: "Grass", type2: "Flying" },
	{ name: "Arceus", id: "arceus", type1: "Normal", type2: "" },
	{ name: "Victini", id: "victini", type1: "Psychic", type2: "Fire" },
	{ name: "Snivy", id: "snivy", type1: "Grass", type2: "" },
	{ name: "Servine", id: "servine", type1: "Grass", type2: "" },
	{ name: "Serperior", id: "serperior", type1: "Grass", type2: "" },
	{ name: "Tepig", id: "tepig", type1: "Fire", type2: "" },
	{ name: "Pignite", id: "pignite", type1: "Fire", type2: "Fighting" },
	{ name: "Emboar", id: "emboar", type1: "Fire", type2: "Fighting" },
	{ name: "Oshawott", id: "oshawott", type1: "Water", type2: "" },
	{ name: "Dewott", id: "dewott", type1: "Water", type2: "" },
	{ name: "Samurott", id: "samurott", type1: "Water", type2: "" },
	{ name: "Patrat", id: "patrat", type1: "Normal", type2: "" },
	{ name: "Watchog", id: "watchog", type1: "Normal", type2: "" },
	{ name: "Lillipup", id: "lillipup", type1: "Normal", type2: "" },
	{ name: "Herdier", id: "herdier", type1: "Normal", type2: "" },
	{ name: "Stoutland", id: "stoutland", type1: "Normal", type2: "" },
	{ name: "Purrloin", id: "purrloin", type1: "Dark", type2: "" },
	{ name: "Liepard", id: "liepard", type1: "Dark", type2: "" },
	{ name: "Pansage", id: "pansage", type1: "Grass", type2: "" },
	{ name: "Simisage", id: "simisage", type1: "Grass", type2: "" },
	{ name: "Pansear", id: "pansear", type1: "Fire", type2: "" },
	{ name: "Simisear", id: "simisear", type1: "Fire", type2: "" },
	{ name: "Panpour", id: "panpour", type1: "Water", type2: "" },
	{ name: "Simipour", id: "simipour", type1: "Water", type2: "" },
	{ name: "Munna", id: "munna", type1: "Psychic", type2: "" },
	{ name: "Musharna", id: "musharna", type1: "Psychic", type2: "" },
	{ name: "Pidove", id: "pidove", type1: "Normal", type2: "Flying" },
	{ name: "Tranquill", id: "tranquill", type1: "Normal", type2: "Flying" },
	{ name: "Unfezant", id: "unfezant", type1: "Normal", type2: "Flying" },
	{ name: "Blitzle", id: "blitzle", type1: "Electric", type2: "" },
	{ name: "Zebstrika", id: "zebstrika", type1: "Electric", type2: "" },
	{ name: "Roggenrola", id: "roggenrola", type1: "Rock", type2: "" },
	{ name: "Boldore", id: "boldore", type1: "Rock", type2: "" },
	{ name: "Gigalith", id: "gigalith", type1: "Rock", type2: "" },
	{ name: "Woobat", id: "woobat", type1: "Psychic", type2: "Flying" },
	{ name: "Swoobat", id: "swoobat", type1: "Psychic", type2: "Flying" },
	{ name: "Drilbur", id: "drilbur", type1: "Ground", type2: "" },
	{ name: "Excadrill", id: "excadrill", type1: "Ground", type2: "Steel" },
	{ name: "Audino", id: "audino", type1: "Normal", type2: "" },
	{ name: "Mega Audino", id: "audino-mega", type1: "Normal", type2: "Fairy" },
	{ name: "Timburr", id: "timburr", type1: "Fighting", type2: "" },
	{ name: "Gurdurr", id: "gurdurr", type1: "Fighting", type2: "" },
	{ name: "Conkeldurr", id: "conkeldurr", type1: "Fighting", type2: "" },
	{ name: "Tympole", id: "tympole", type1: "Water", type2: "" },
	{ name: "Palpitoad", id: "palpitoad", type1: "Water", type2: "Ground" },
	{ name: "Seismitoad", id: "seismitoad", type1: "Water", type2: "Ground" },
	{ name: "Throh", id: "throh", type1: "Fighting", type2: "" },
	{ name: "Sawk", id: "sawk", type1: "Fighting", type2: "" },
	{ name: "Sewaddle", id: "sewaddle", type1: "Bug", type2: "Grass" },
	{ name: "Swadloon", id: "swadloon", type1: "Bug", type2: "Grass" },
	{ name: "Leavanny", id: "leavanny", type1: "Bug", type2: "Grass" },
	{ name: "Venipede", id: "venipede", type1: "Bug", type2: "Poison" },
	{ name: "Whirlipede", id: "whirlipede", type1: "Bug", type2: "Poison" },
	{ name: "Scolipede", id: "scolipede", type1: "Bug", type2: "Poison" },
	{ name: "Cottonee", id: "cottonee", type1: "Grass", type2: "Fairy" },
	{ name: "Whimsicott", id: "whimsicott", type1: "Grass", type2: "Fairy" },
	{ name: "Petilil", id: "petilil", type1: "Grass", type2: "" },
	{ name: "Lilligant", id: "lilligant", type1: "Grass", type2: "" },
	{
		name: "Basculin Red-Striped",
		id: "basculin red-striped",
		type1: "Water",
		type2: "",
	},
	{
		name: "Basculin Blue-Striped",
		id: "basculin blue-striped",
		type1: "Water",
		type2: "",
	},
	{ name: "Sandile", id: "sandile", type1: "Ground", type2: "Dark" },
	{ name: "Krokorok", id: "krokorok", type1: "Ground", type2: "Dark" },
	{ name: "Krookodile", id: "krookodile", type1: "Ground", type2: "Dark" },
	{ name: "Darumaka", id: "darumaka", type1: "Fire", type2: "" },
	{
		name: "Galarian Darumaka",
		id: "galarian darumaka",
		type1: "Ice",
		type2: "",
	},
	{ name: "Darmanitan", id: "darmanitan", type1: "Fire", type2: "" },
	{
		name: "Darmanitan Zen",
		id: "darmanitan zen",
		type1: "Fire",
		type2: "Psychic",
	},
	{
		name: "Galarian Darmanitan",
		id: "galarian darmanitan",
		type1: "Ice",
		type2: "",
	},
	{
		name: "Galarian Darmanitan Zen",
		id: "galarian darmanitan zen",
		type1: "Ice",
		type2: "Fire",
	},
	{ name: "Maractus", id: "maractus", type1: "Grass", type2: "" },
	{ name: "Dwebble", id: "dwebble", type1: "Bug", type2: "Rock" },
	{ name: "Crustle", id: "crustle", type1: "Bug", type2: "Rock" },
	{ name: "Scraggy", id: "scraggy", type1: "Dark", type2: "Fighting" },
	{ name: "Scrafty", id: "scrafty", type1: "Dark", type2: "Fighting" },
	{ name: "Sigilyph", id: "sigilyph", type1: "Psychic", type2: "Flying" },
	{ name: "Yamask", id: "yamask", type1: "Ghost", type2: "" },
	{
		name: "Galarian Yamask",
		id: "galarian yamask",
		type1: "Ground",
		type2: "Ghost",
	},
	{ name: "Cofagrigus", id: "cofagrigus", type1: "Ghost", type2: "" },
	{ name: "Tirtouga", id: "tirtouga", type1: "Water", type2: "Rock" },
	{ name: "Carracosta", id: "carracosta", type1: "Water", type2: "Rock" },
	{ name: "Archen", id: "archen", type1: "Rock", type2: "Flying" },
	{ name: "Archeops", id: "archeops", type1: "Rock", type2: "Flying" },
	{ name: "Trubbish", id: "trubbish", type1: "Poison", type2: "" },
	{ name: "Garbodor", id: "garbodor", type1: "Poison", type2: "" },
	{
		name: "Gigantamax Garbodor",
		id: "gigantamax garbodor",
		type1: "Poison",
		type2: "",
	},
	{ name: "Zorua", id: "zorua", type1: "Dark", type2: "" },
	{ name: "Zoroark", id: "zoroark", type1: "Dark", type2: "" },
	{ name: "Minccino", id: "minccino", type1: "Normal", type2: "" },
	{ name: "Cinccino", id: "cinccino", type1: "Normal", type2: "" },
	{ name: "Gothita", id: "gothita", type1: "Psychic", type2: "" },
	{ name: "Gothorita", id: "gothorita", type1: "Psychic", type2: "" },
	{ name: "Gothitelle", id: "gothitelle", type1: "Psychic", type2: "" },
	{ name: "Solosis", id: "solosis", type1: "Psychic", type2: "" },
	{ name: "Duosion", id: "duosion", type1: "Psychic", type2: "" },
	{ name: "Reuniclus", id: "reuniclus", type1: "Psychic", type2: "" },
	{ name: "Ducklett", id: "ducklett", type1: "Water", type2: "Flying" },
	{ name: "Swanna", id: "swanna", type1: "Water", type2: "Flying" },
	{ name: "Vanillite", id: "vanillite", type1: "Ice", type2: "" },
	{ name: "Vanillish", id: "vanillish", type1: "Ice", type2: "" },
	{ name: "Vanilluxe", id: "vanilluxe", type1: "Ice", type2: "" },
	{
		name: "Deerling Spring",
		id: "deerling spring",
		type1: "Normal",
		type2: "Grass",
	},
	{
		name: "Deerling Summer",
		id: "deerling summer",
		type1: "Normal",
		type2: "Grass",
	},
	{
		name: "Deerling Autumn",
		id: "deerling autumn",
		type1: "Normal",
		type2: "Grass",
	},
	{
		name: "Deerling Winter",
		id: "deerling winter",
		type1: "Normal",
		type2: "Grass",
	},
	{
		name: "Sawsbuck Spring",
		id: "sawsbuck spring",
		type1: "Normal",
		type2: "Grass",
	},
	{
		name: "Sawsbuck Summer",
		id: "sawsbuck summer",
		type1: "Normal",
		type2: "Grass",
	},
	{
		name: "Sawsbuck Autumn",
		id: "sawsbuck autumn",
		type1: "Normal",
		type2: "Grass",
	},
	{
		name: "Sawsbuck Winter",
		id: "sawsbuck winter",
		type1: "Normal",
		type2: "Grass",
	},
	{ name: "Emolga", id: "emolga", type1: "Electric", type2: "Flying" },
	{ name: "Karrablast", id: "karrablast", type1: "Bug", type2: "" },
	{ name: "Escavalier", id: "escavalier", type1: "Bug", type2: "Steel" },
	{ name: "Foongus", id: "foongus", type1: "Grass", type2: "Poison" },
	{ name: "Amoonguss", id: "amoonguss", type1: "Grass", type2: "Poison" },
	{ name: "Frillish", id: "frillish", type1: "Water", type2: "Ghost" },
	{ name: "Jellicent", id: "jellicent", type1: "Water", type2: "Ghost" },
	{ name: "Alomomola", id: "alomomola", type1: "Water", type2: "" },
	{ name: "Joltik", id: "joltik", type1: "Bug", type2: "Electric" },
	{ name: "Galvantula", id: "galvantula", type1: "Bug", type2: "Electric" },
	{ name: "Ferroseed", id: "ferroseed", type1: "Grass", type2: "Steel" },
	{ name: "Ferrothorn", id: "ferrothorn", type1: "Grass", type2: "Steel" },
	{ name: "Klink", id: "klink", type1: "Steel", type2: "" },
	{ name: "Klang", id: "klang", type1: "Steel", type2: "" },
	{ name: "Klinklang", id: "klinklang", type1: "Steel", type2: "" },
	{ name: "Tynamo", id: "tynamo", type1: "Electric", type2: "" },
	{ name: "Eelektrik", id: "eelektrik", type1: "Electric", type2: "" },
	{ name: "Eelektross", id: "eelektross", type1: "Electric", type2: "" },
	{ name: "Elgyem", id: "elgyem", type1: "Psychic", type2: "" },
	{ name: "Beheeyem", id: "beheeyem", type1: "Psychic", type2: "" },
	{ name: "Litwick", id: "litwick", type1: "Ghost", type2: "Fire" },
	{ name: "Lampent", id: "lampent", type1: "Ghost", type2: "Fire" },
	{ name: "Chandelure", id: "chandelure", type1: "Ghost", type2: "Fire" },
	{ name: "Axew", id: "axew", type1: "Dragon", type2: "" },
	{ name: "Fraxure", id: "fraxure", type1: "Dragon", type2: "" },
	{ name: "Haxorus", id: "haxorus", type1: "Dragon", type2: "" },
	{ name: "Cubchoo", id: "cubchoo", type1: "Ice", type2: "" },
	{ name: "Beartic", id: "beartic", type1: "Ice", type2: "" },
	{ name: "Cryogonal", id: "cryogonal", type1: "Ice", type2: "" },
	{ name: "Shelmet", id: "shelmet", type1: "Bug", type2: "" },
	{ name: "Accelgor", id: "accelgor", type1: "Bug", type2: "" },
	{ name: "Stunfisk", id: "stunfisk", type1: "Ground", type2: "Electric" },
	{
		name: "Galarian Stunfisk",
		id: "galarian stunfisk",
		type1: "Ground",
		type2: "Steel",
	},
	{ name: "Mienfoo", id: "mienfoo", type1: "Fighting", type2: "" },
	{ name: "Mienshao", id: "mienshao", type1: "Fighting", type2: "" },
	{ name: "Druddigon", id: "druddigon", type1: "Dragon", type2: "" },
	{ name: "Golett", id: "golett", type1: "Ground", type2: "Ghost" },
	{ name: "Golurk", id: "golurk", type1: "Ground", type2: "Ghost" },
	{ name: "Pawniard", id: "pawniard", type1: "Dark", type2: "Steel" },
	{ name: "Bisharp", id: "bisharp", type1: "Dark", type2: "Steel" },
	{ name: "Bouffalant", id: "bouffalant", type1: "Normal", type2: "" },
	{ name: "Rufflet", id: "rufflet", type1: "Normal", type2: "Flying" },
	{ name: "Braviary", id: "braviary", type1: "Normal", type2: "Flying" },
	{ name: "Vullaby", id: "vullaby", type1: "Dark", type2: "Flying" },
	{ name: "Mandibuzz", id: "mandibuzz", type1: "Dark", type2: "Flying" },
	{ name: "Heatmor", id: "heatmor", type1: "Fire", type2: "" },
	{ name: "Durant", id: "durant", type1: "Bug", type2: "Steel" },
	{ name: "Deino", id: "deino", type1: "Dark", type2: "Dragon" },
	{ name: "Zweilous", id: "zweilous", type1: "Dark", type2: "Dragon" },
	{ name: "Hydreigon", id: "hydreigon", type1: "Dark", type2: "Dragon" },
	{ name: "Larvesta", id: "larvesta", type1: "Bug", type2: "Fire" },
	{ name: "Volcarona", id: "volcarona", type1: "Bug", type2: "Fire" },
	{ name: "Cobalion", id: "cobalion", type1: "Steel", type2: "Fighting" },
	{ name: "Terrakion", id: "terrakion", type1: "Rock", type2: "Fighting" },
	{ name: "Virizion", id: "virizion", type1: "Grass", type2: "Fighting" },
	{
		name: "Tornadus Incarnate",
		id: "tornadus incarnate",
		type1: "Flying",
		type2: "",
	},
	{ name: "Tornadus", id: "tornadus", type1: "Flying", type2: "" },
	{
		name: "Tornadus Therian",
		id: "tornadus therian",
		type1: "Flying",
		type2: "",
	},
	{
		name: "Thundurus Incarnate",
		id: "thundurus incarnate",
		type1: "Electric",
		type2: "Flying",
	},
	{ name: "Thundurus", id: "thundurus", type1: "Electric", type2: "Flying" },
	{
		name: "Thundurus Therian",
		id: "thundurus therian",
		type1: "Electric",
		type2: "Flying",
	},
	{ name: "Reshiram", id: "reshiram", type1: "Dragon", type2: "Fire" },
	{ name: "Zekrom", id: "zekrom", type1: "Dragon", type2: "Electric" },
	{
		name: "Landorus Incarnate",
		id: "landorus incarnate",
		type1: "Ground",
		type2: "Flying",
	},
	{ name: "Landorus", id: "landorus", type1: "Ground", type2: "Flying" },
	{
		name: "Landorus Therian",
		id: "landorus therian",
		type1: "Ground",
		type2: "Flying",
	},
	{ name: "Kyurem", id: "kyurem", type1: "Dragon", type2: "Ice" },
	{ name: "Kyurem White", id: "kyurem white", type1: "Dragon", type2: "Ice" },
	{ name: "Kyurem Black", id: "kyurem black", type1: "Dragon", type2: "Ice" },
	{
		name: "Keldeo Ordinary",
		id: "keldeo ordinary",
		type1: "Water",
		type2: "Fighting",
	},
	{ name: "Keldeo", id: "keldeo", type1: "Water", type2: "Fighting" },
	{
		name: "Keldeo Resolute",
		id: "keldeo resolute",
		type1: "Water",
		type2: "Fighting",
	},
	{
		name: "Meloetta Aria",
		id: "meloetta aria",
		type1: "Normal",
		type2: "Psychic",
	},
	{
		name: "Meloetta Pirouette",
		id: "meloetta pirouette",
		type1: "Normal",
		type2: "Fighting",
	},
	{ name: "Genesect", id: "genesect", type1: "Bug", type2: "Steel" },
	{
		name: "Genesect Shock Drive",
		id: "genesect shock drive",
		type1: "Bug",
		type2: "Steel",
	},
	{
		name: "Genesect Burn Drive",
		id: "genesect burn drive",
		type1: "Bug",
		type2: "Steel",
	},
	{
		name: "Genesect Chill Drive",
		id: "genesect chill drive",
		type1: "Bug",
		type2: "Steel",
	},
	{
		name: "Genesect Douse Drive",
		id: "genesect douse drive",
		type1: "Bug",
		type2: "Steel",
	},
	{ name: "Chespin", id: "chespin", type1: "Grass", type2: "" },
	{ name: "Quilladin", id: "quilladin", type1: "Grass", type2: "" },
	{ name: "Chesnaught", id: "chesnaught", type1: "Grass", type2: "Fighting" },
	{ name: "Fennekin", id: "fennekin", type1: "Fire", type2: "" },
	{ name: "Braixen", id: "braixen", type1: "Fire", type2: "" },
	{ name: "Delphox", id: "delphox", type1: "Fire", type2: "Psychic" },
	{ name: "Froakie", id: "froakie", type1: "Water", type2: "" },
	{ name: "Frogadier", id: "frogadier", type1: "Water", type2: "" },
	{ name: "Greninja", id: "greninja", type1: "Water", type2: "Dark" },
	{ name: "Ash-Greninja", id: "ash-greninja", type1: "Water", type2: "Dark" },
	{ name: "Bunnelby", id: "bunnelby", type1: "Normal", type2: "" },
	{ name: "Diggersby", id: "diggersby", type1: "Normal", type2: "Ground" },
	{ name: "Fletchling", id: "fletchling", type1: "Normal", type2: "Flying" },
	{ name: "Fletchinder", id: "fletchinder", type1: "Fire", type2: "Flying" },
	{ name: "Talonflame", id: "talonflame", type1: "Fire", type2: "Flying" },
	{ name: "Scatterbug", id: "scatterbug", type1: "Bug", type2: "" },
	{ name: "Spewpa", id: "spewpa", type1: "Bug", type2: "" },
	{
		name: "Vivillon Archipelago Pattern",
		id: "vivillon archipelago pattern",
		type1: "Bug",
		type2: "Flying",
	},
	{
		name: "Vivillon Continental Pattern",
		id: "vivillon continental pattern",
		type1: "Bug",
		type2: "Flying",
	},
	{
		name: "Vivillon Elegant Pattern",
		id: "vivillon elegant pattern",
		type1: "Bug",
		type2: "Flying",
	},
	{
		name: "Vivillon Fancy Pattern",
		id: "vivillon fancy pattern",
		type1: "Bug",
		type2: "Flying",
	},
	{
		name: "Vivillon Garden Pattern",
		id: "vivillon garden pattern",
		type1: "Bug",
		type2: "Flying",
	},
	{
		name: "Vivillon High Plains Pattern",
		id: "vivillon high plains pattern",
		type1: "Bug",
		type2: "Flying",
	},
	{
		name: "Vivillon Icy Snow Pattern",
		id: "vivillon icy snow pattern",
		type1: "Bug",
		type2: "Flying",
	},
	{
		name: "Vivillon Jungle Pattern",
		id: "vivillon jungle pattern",
		type1: "Bug",
		type2: "Flying",
	},
	{
		name: "Vivillon Marine Pattern",
		id: "vivillon marine pattern",
		type1: "Bug",
		type2: "Flying",
	},
	{
		name: "Vivillon Meadow Pattern",
		id: "vivillon meadow pattern",
		type1: "Bug",
		type2: "Flying",
	},
	{
		name: "Vivillon Modern Pattern",
		id: "vivillon modern pattern",
		type1: "Bug",
		type2: "Flying",
	},
	{
		name: "Vivillon Monsoon Pattern",
		id: "vivillon monsoon pattern",
		type1: "Bug",
		type2: "Flying",
	},
	{
		name: "Vivillon Ocean Pattern",
		id: "vivillon ocean pattern",
		type1: "Bug",
		type2: "Flying",
	},
	{
		name: "Vivillon Poké Ball Pattern",
		id: "vivillon poké ball pattern",
		type1: "Bug",
		type2: "Flying",
	},
	{
		name: "Vivillon Polar Pattern",
		id: "vivillon polar pattern",
		type1: "Bug",
		type2: "Flying",
	},
	{
		name: "Vivillon River Pattern",
		id: "vivillon river pattern",
		type1: "Bug",
		type2: "Flying",
	},
	{
		name: "Vivillon Sandstorm Pattern",
		id: "vivillon sandstorm pattern",
		type1: "Bug",
		type2: "Flying",
	},
	{
		name: "Vivillon Savanna Pattern",
		id: "vivillon savanna pattern",
		type1: "Bug",
		type2: "Flying",
	},
	{
		name: "Vivillon Sun Pattern",
		id: "vivillon sun pattern",
		type1: "Bug",
		type2: "Flying",
	},
	{
		name: "Vivillon Tundra Pattern",
		id: "vivillon tundra pattern",
		type1: "Bug",
		type2: "Flying",
	},
	{ name: "Litleo", id: "litleo", type1: "Fire", type2: "Normal" },
	{ name: "Pyroar", id: "pyroar", type1: "Fire", type2: "Normal" },
	{
		name: "Flabébé Red Flower",
		id: "flabébé red flower",
		type1: "Fairy",
		type2: "",
	},
	{
		name: "Flabébé Yellow Flower",
		id: "flabébé yellow flower",
		type1: "Fairy",
		type2: "",
	},
	{
		name: "Flabébé Orange Flower",
		id: "flabébé orange flower",
		type1: "Fairy",
		type2: "",
	},
	{
		name: "Flabébé Blue Flower",
		id: "flabébé blue flower",
		type1: "Fairy",
		type2: "",
	},
	{
		name: "Flabébé White Flower",
		id: "flabébé white flower",
		type1: "Fairy",
		type2: "",
	},
	{
		name: "Floette Red Flower",
		id: "floette red flower",
		type1: "Fairy",
		type2: "",
	},
	{
		name: "Floette Yellow Flower",
		id: "floette yellow flower",
		type1: "Fairy",
		type2: "",
	},
	{
		name: "Floette Orange Flower",
		id: "floette orange flower",
		type1: "Fairy",
		type2: "",
	},
	{
		name: "Floette Blue Flower",
		id: "floette blue flower",
		type1: "Fairy",
		type2: "",
	},
	{
		name: "Floette White Flower",
		id: "floette white flower",
		type1: "Fairy",
		type2: "",
	},
	{
		name: "Floette Eternal Flower",
		id: "floette eternal flower",
		type1: "Fairy",
		type2: "",
	},
	{
		name: "Florges Red Flower",
		id: "florges red flower",
		type1: "Fairy",
		type2: "",
	},
	{
		name: "Florges Yellow Flower",
		id: "florges yellow flower",
		type1: "Fairy",
		type2: "",
	},
	{
		name: "Florges Orange Flower",
		id: "florges orange flower",
		type1: "Fairy",
		type2: "",
	},
	{
		name: "Florges Blue Flower",
		id: "florges blue flower",
		type1: "Fairy",
		type2: "",
	},
	{
		name: "Florges White Flower",
		id: "florges white flower",
		type1: "Fairy",
		type2: "",
	},
	{ name: "Skiddo", id: "skiddo", type1: "Grass", type2: "" },
	{ name: "Gogoat", id: "gogoat", type1: "Grass", type2: "" },
	{ name: "Pancham", id: "pancham", type1: "Fighting", type2: "" },
	{ name: "Pangoro", id: "pangoro", type1: "Fighting", type2: "Dark" },
	{
		name: "Furfrou Natural Form",
		id: "furfrou natural form",
		type1: "Normal",
		type2: "",
	},
	{
		name: "Furfrou Heart Trim",
		id: "furfrou heart trim",
		type1: "Normal",
		type2: "",
	},
	{
		name: "Furfrou Star Trim",
		id: "furfrou star trim",
		type1: "Normal",
		type2: "",
	},
	{
		name: "Furfrou Diamond Trim",
		id: "furfrou diamond trim",
		type1: "Normal",
		type2: "",
	},
	{
		name: "Furfrou Debutante Trim",
		id: "furfrou debutante trim",
		type1: "Normal",
		type2: "",
	},
	{
		name: "Furfrou Matron Trim",
		id: "furfrou matron trim",
		type1: "Normal",
		type2: "",
	},
	{
		name: "Furfrou Dandy Trim",
		id: "furfrou dandy trim",
		type1: "Normal",
		type2: "",
	},
	{
		name: "Furfrou La Reine Trim",
		id: "furfrou la reine trim",
		type1: "Normal",
		type2: "",
	},
	{
		name: "Furfrou Kabuki Trim",
		id: "furfrou kabuki trim",
		type1: "Normal",
		type2: "",
	},
	{
		name: "Furfrou Pharaoh Trim",
		id: "furfrou pharaoh trim",
		type1: "Normal",
		type2: "",
	},
	{ name: "Espurr", id: "espurr", type1: "Psychic", type2: "" },
	{ name: "Meowstic Male", id: "meowstic male", type1: "Psychic", type2: "" },
	{
		name: "Meowstic Female",
		id: "meowstic female",
		type1: "Psychic",
		type2: "",
	},
	{ name: "Honedge", id: "honedge", type1: "Steel", type2: "Ghost" },
	{ name: "Doublade", id: "doublade", type1: "Steel", type2: "Ghost" },
	{
		name: "Aegislash Shield",
		id: "aegislash shield",
		type1: "Steel",
		type2: "Ghost",
	},
	{
		name: "Aegislash Blade",
		id: "aegislash blade",
		type1: "Steel",
		type2: "Ghost",
	},
	{ name: "Spritzee", id: "spritzee", type1: "Fairy", type2: "" },
	{ name: "Aromatisse", id: "aromatisse", type1: "Fairy", type2: "" },
	{ name: "Swirlix", id: "swirlix", type1: "Fairy", type2: "" },
	{ name: "Slurpuff", id: "slurpuff", type1: "Fairy", type2: "" },
	{ name: "Inkay", id: "inkay", type1: "Dark", type2: "Psychic" },
	{ name: "Malamar", id: "malamar", type1: "Dark", type2: "Psychic" },
	{ name: "Binacle", id: "binacle", type1: "Rock", type2: "Water" },
	{ name: "Barbaracle", id: "barbaracle", type1: "Rock", type2: "Water" },
	{ name: "Skrelp", id: "skrelp", type1: "Poison", type2: "Water" },
	{ name: "Dragalge", id: "dragalge", type1: "Poison", type2: "Dragon" },
	{ name: "Clauncher", id: "clauncher", type1: "Water", type2: "" },
	{ name: "Clawitzer", id: "clawitzer", type1: "Water", type2: "" },
	{ name: "Helioptile", id: "helioptile", type1: "Electric", type2: "Normal" },
	{ name: "Heliolisk", id: "heliolisk", type1: "Electric", type2: "Normal" },
	{ name: "Tyrunt", id: "tyrunt", type1: "Rock", type2: "Dragon" },
	{ name: "Tyrantrum", id: "tyrantrum", type1: "Rock", type2: "Dragon" },
	{ name: "Amaura", id: "amaura", type1: "Rock", type2: "Ice" },
	{ name: "Aurorus", id: "aurorus", type1: "Rock", type2: "Ice" },
	{ name: "Sylveon", id: "sylveon", type1: "Fairy", type2: "" },
	{ name: "Hawlucha", id: "hawlucha", type1: "Fighting", type2: "Flying" },
	{ name: "Dedenne", id: "dedenne", type1: "Electric", type2: "Fairy" },
	{ name: "Carbink", id: "carbink", type1: "Rock", type2: "Fairy" },
	{ name: "Goomy", id: "goomy", type1: "Dragon", type2: "" },
	{ name: "Sliggoo", id: "sliggoo", type1: "Dragon", type2: "" },
	{ name: "Goodra", id: "goodra", type1: "Dragon", type2: "" },
	{ name: "Klefki", id: "klefki", type1: "Steel", type2: "Fairy" },
	{ name: "Phantump", id: "phantump", type1: "Ghost", type2: "Grass" },
	{ name: "Trevenant", id: "trevenant", type1: "Ghost", type2: "Grass" },
	{
		name: "Pumpkaboo Average Size",
		id: "pumpkaboo average size",
		type1: "Ghost",
		type2: "Grass",
	},
	{ name: "Pumpkaboo", id: "pumpkaboo", type1: "Ghost", type2: "Grass" },
	{
		name: "Pumpkaboo Small Size",
		id: "pumpkaboo small size",
		type1: "Ghost",
		type2: "Grass",
	},
	{
		name: "Pumpkaboo Large Size",
		id: "pumpkaboo large size",
		type1: "Ghost",
		type2: "Grass",
	},
	{
		name: "Pumpkaboo Super Size",
		id: "pumpkaboo super size",
		type1: "Ghost",
		type2: "Grass",
	},
	{
		name: "Gourgeist Average Size",
		id: "gourgeist average size",
		type1: "Ghost",
		type2: "Grass",
	},
	{ name: "Gourgeist", id: "gourgeist", type1: "Ghost", type2: "Grass" },
	{
		name: "Gourgeist Small Size",
		id: "gourgeist small size",
		type1: "Ghost",
		type2: "Grass",
	},
	{
		name: "Gourgeist Large Size",
		id: "gourgeist large size",
		type1: "Ghost",
		type2: "Grass",
	},
	{
		name: "Gourgeist Super Size",
		id: "gourgeist super size",
		type1: "Ghost",
		type2: "Grass",
	},
	{ name: "Bergmite", id: "bergmite", type1: "Ice", type2: "" },
	{ name: "Avalugg", id: "avalugg", type1: "Ice", type2: "" },
	{ name: "Noibat", id: "noibat", type1: "Flying", type2: "Dragon" },
	{ name: "Noivern", id: "noivern", type1: "Flying", type2: "Dragon" },
	{ name: "Xerneas Active", id: "xerneas active", type1: "Fairy", type2: "" },
	{ name: "Xerneas", id: "xerneas", type1: "Fairy", type2: "" },
	{ name: "Xerneas Neutral", id: "xerneas neutral", type1: "Fairy", type2: "" },
	{ name: "Yveltal", id: "yveltal", type1: "Dark", type2: "Flying" },
	{ name: "Zygarde 50%", id: "zygarde 50%", type1: "Dragon", type2: "Ground" },
	{ name: "Zygarde", id: "zygarde", type1: "Dragon", type2: "Ground" },
	{ name: "Zygarde 10%", id: "zygarde 10%", type1: "Dragon", type2: "Ground" },
	{
		name: "Zygarde Complete Form",
		id: "zygarde complete form",
		type1: "Dragon",
		type2: "Ground",
	},
	{ name: "Diancie", id: "diancie", type1: "Rock", type2: "Fairy" },
	{ name: "Mega Diancie", id: "mega diancie", type1: "Rock", type2: "Fairy" },
	{
		name: "Hoopa Confined",
		id: "hoopa confined",
		type1: "Psychic",
		type2: "Ghost",
	},
	{ name: "Hoopa", id: "hoopa", type1: "Psychic", type2: "Ghost" },
	{
		name: "Hoopa Unbound",
		id: "hoopa unbound",
		type1: "Psychic",
		type2: "Dark",
	},
	{ name: "Volcanion", id: "volcanion", type1: "Fire", type2: "Water" },
	{ name: "Rowlet", id: "rowlet", type1: "Grass", type2: "Flying" },
	{ name: "Dartrix", id: "dartrix", type1: "Grass", type2: "Flying" },
	{ name: "Decidueye", id: "decidueye", type1: "Grass", type2: "Ghost" },
	{ name: "Litten", id: "litten", type1: "Fire", type2: "" },
	{ name: "Torracat", id: "torracat", type1: "Fire", type2: "" },
	{ name: "Incineroar", id: "incineroar", type1: "Fire", type2: "Dark" },
	{ name: "Popplio", id: "popplio", type1: "Water", type2: "" },
	{ name: "Brionne", id: "brionne", type1: "Water", type2: "" },
	{ name: "Primarina", id: "primarina", type1: "Water", type2: "Fairy" },
	{ name: "Pikipek", id: "pikipek", type1: "Normal", type2: "Flying" },
	{ name: "Trumbeak", id: "trumbeak", type1: "Normal", type2: "Flying" },
	{ name: "Toucannon", id: "toucannon", type1: "Normal", type2: "Flying" },
	{ name: "Yungoos", id: "yungoos", type1: "Normal", type2: "" },
	{ name: "Gumshoos", id: "gumshoos", type1: "Normal", type2: "" },
	{ name: "Grubbin", id: "grubbin", type1: "Bug", type2: "" },
	{ name: "Charjabug", id: "charjabug", type1: "Bug", type2: "Electric" },
	{ name: "Vikavolt", id: "vikavolt", type1: "Bug", type2: "Electric" },
	{ name: "Crabrawler", id: "crabrawler", type1: "Fighting", type2: "" },
	{ name: "Crabominable", id: "crabominable", type1: "Fighting", type2: "Ice" },
	{
		name: "Oricorio Baile Style",
		id: "oricorio baile style",
		type1: "Fire",
		type2: "Flying",
	},
	{
		name: "Oricorio Pom-Pom Style",
		id: "oricorio pom-pom style",
		type1: "Electric",
		type2: "Flying",
	},
	{
		name: "Oricorio Pa'u Style",
		id: "oricorio pa'u style",
		type1: "Psychic",
		type2: "Flying",
	},
	{
		name: "Oricorio Sensu Style",
		id: "oricorio sensu style",
		type1: "Ghost",
		type2: "Flying",
	},
	{ name: "Cutiefly", id: "cutiefly", type1: "Bug", type2: "Fairy" },
	{ name: "Ribombee", id: "ribombee", type1: "Bug", type2: "Fairy" },
	{ name: "Rockruff", id: "rockruff", type1: "Rock", type2: "" },
	{ name: "Lycanroc Midday", id: "lycanroc midday", type1: "Rock", type2: "" },
	{
		name: "Lycanroc Midnight",
		id: "lycanroc midnight",
		type1: "Rock",
		type2: "",
	},
	{ name: "Lycanroc Dusk", id: "lycanroc dusk", type1: "Rock", type2: "" },
	{ name: "Wishiwashi Solo Form", id: "wishiwashi", type1: "Water", type2: "" },
	{
		name: "Wishiwashi School Form",
		id: "wishiwashi school form",
		type1: "Water",
		type2: "",
	},
	{ name: "Mareanie", id: "mareanie", type1: "Poison", type2: "Water" },
	{ name: "Toxapex", id: "toxapex", type1: "Poison", type2: "Water" },
	{ name: "Mudbray", id: "mudbray", type1: "Ground", type2: "" },
	{ name: "Mudsdale", id: "mudsdale", type1: "Ground", type2: "" },
	{ name: "Dewpider", id: "dewpider", type1: "Water", type2: "Bug" },
	{ name: "Araquanid", id: "araquanid", type1: "Water", type2: "Bug" },
	{ name: "Fomantis", id: "fomantis", type1: "Grass", type2: "" },
	{ name: "Lurantis", id: "lurantis", type1: "Grass", type2: "" },
	{ name: "Morelull", id: "morelull", type1: "Grass", type2: "Fairy" },
	{ name: "Shiinotic", id: "shiinotic", type1: "Grass", type2: "Fairy" },
	{ name: "Salandit", id: "salandit", type1: "Poison", type2: "Fire" },
	{ name: "Salazzle", id: "salazzle", type1: "Poison", type2: "Fire" },
	{ name: "Stufful", id: "stufful", type1: "Normal", type2: "Fighting" },
	{ name: "Bewear", id: "bewear", type1: "Normal", type2: "Fighting" },
	{ name: "Bounsweet", id: "bounsweet", type1: "Grass", type2: "" },
	{ name: "Steenee", id: "steenee", type1: "Grass", type2: "" },
	{ name: "Tsareena", id: "tsareena", type1: "Grass", type2: "" },
	{ name: "Comfey", id: "comfey", type1: "Fairy", type2: "" },
	{ name: "Oranguru", id: "oranguru", type1: "Normal", type2: "Psychic" },
	{ name: "Passimian", id: "passimian", type1: "Fighting", type2: "" },
	{ name: "Wimpod", id: "wimpod", type1: "Bug", type2: "Water" },
	{ name: "Golisopod", id: "golisopod", type1: "Bug", type2: "Water" },
	{ name: "Sandygast", id: "sandygast", type1: "Ghost", type2: "Ground" },
	{ name: "Palossand", id: "palossand", type1: "Ghost", type2: "Ground" },
	{ name: "Pyukumuku", id: "pyukumuku", type1: "Water", type2: "" },
	{ name: "Type: Null", id: "type: null", type1: "Normal", type2: "" },
	{ name: "Silvally", id: "silvally", type1: "Normal", type2: "" },
	{
		name: "Minior Meteor Form",
		id: "minior meteor form",
		type1: "Rock",
		type2: "Flying",
	},
	{
		name: "Minior Red Core",
		id: "minior red core",
		type1: "Rock",
		type2: "Flying",
	},
	{
		name: "Minior Orange Core",
		id: "minior orange core",
		type1: "Rock",
		type2: "Flying",
	},
	{
		name: "Minior Yellow Core",
		id: "minior yellow core",
		type1: "Rock",
		type2: "Flying",
	},
	{
		name: "Minior Green Core",
		id: "minior green core",
		type1: "Rock",
		type2: "Flying",
	},
	{
		name: "Minior Blue Core",
		id: "minior blue core",
		type1: "Rock",
		type2: "Flying",
	},
	{
		name: "Minior Indigo Core",
		id: "minior indigo core",
		type1: "Rock",
		type2: "Flying",
	},
	{
		name: "Minior Violet Core",
		id: "minior violet core",
		type1: "Rock",
		type2: "Flying",
	},
	{ name: "Komala", id: "komala", type1: "Normal", type2: "" },
	{ name: "Turtonator", id: "turtonator", type1: "Fire", type2: "Dragon" },
	{ name: "Togedemaru", id: "togedemaru", type1: "Electric", type2: "Steel" },
	{
		name: "Mimikyu Disguised",
		id: "mimikyu disguised",
		type1: "Ghost",
		type2: "Fairy",
	},
	{
		name: "Mimikyu Busted",
		id: "mimikyu busted",
		type1: "Ghost",
		type2: "Fairy",
	},
	{ name: "Bruxish", id: "bruxish", type1: "Water", type2: "Psychic" },
	{ name: "Drampa", id: "drampa", type1: "Normal", type2: "Dragon" },
	{ name: "Dhelmise", id: "dhelmise", type1: "Ghost", type2: "Grass" },
	{ name: "Jangmo-o", id: "jangmo-o", type1: "Dragon", type2: "" },
	{ name: "Hakamo-o", id: "hakamo-o", type1: "Dragon", type2: "Fighting" },
	{ name: "Kommo-o", id: "kommo-o", type1: "Dragon", type2: "Fighting" },
	{ name: "Tapu Koko", id: "tapu koko", type1: "Electric", type2: "Fairy" },
	{ name: "Tapu Lele", id: "tapu lele", type1: "Psychic", type2: "Fairy" },
	{ name: "Tapu Bulu", id: "tapu bulu", type1: "Grass", type2: "Fairy" },
	{ name: "Tapu Fini", id: "tapu fini", type1: "Water", type2: "Fairy" },
	{ name: "Cosmog", id: "cosmog", type1: "Psychic", type2: "" },
	{ name: "Cosmoem", id: "cosmoem", type1: "Psychic", type2: "" },
	{ name: "Solgaleo", id: "solgaleo", type1: "Psychic", type2: "Steel" },
	{ name: "Lunala", id: "lunala", type1: "Psychic", type2: "Ghost" },
	{
		name: "Nihilego [Symbiont]",
		id: "nihilego [symbiont]",
		type1: "Rock",
		type2: "Poison",
	},
	{ name: "Nihilego", id: "nihilego", type1: "Rock", type2: "Poison" },
	{
		name: "Buzzwole [Absorption]",
		id: "buzzwole [absorption]",
		type1: "Bug",
		type2: "Fighting",
	},
	{ name: "Buzzwole", id: "buzzwole", type1: "Bug", type2: "Fighting" },
	{
		name: "Pheromosa [Beauty]",
		id: "pheromosa [beauty]",
		type1: "Bug",
		type2: "Fighting",
	},
	{ name: "Pheromosa", id: "pheromosa", type1: "Bug", type2: "Fighting" },
	{
		name: "Xurkitree [Lighting]",
		id: "xurkitree [lighting]",
		type1: "Electric",
		type2: "",
	},
	{ name: "Xurkitree", id: "xurkitree", type1: "Electric", type2: "" },
	{
		name: "Celesteela [Blaster]",
		id: "celesteela [blaster]",
		type1: "Steel",
		type2: "Flying",
	},
	{ name: "Celesteela", id: "celesteela", type1: "Steel", type2: "Flying" },
	{
		name: "Kartana [Blade]",
		id: "kartana [blade]",
		type1: "Grass",
		type2: "Steel",
	},
	{ name: "Kartana", id: "kartana", type1: "Grass", type2: "Steel" },
	{
		name: "Guzzlord [Glutton]",
		id: "guzzlord [glutton]",
		type1: "Dark",
		type2: "Dragon",
	},
	{ name: "Guzzlord", id: "guzzlord", type1: "Dark", type2: "Dragon" },
	{ name: "Necrozma", id: "necrozma", type1: "Psychic", type2: "" },
	{
		name: "Dusk Mane Necrozma",
		id: "dusk mane necrozma",
		type1: "Psychic",
		type2: "Steel",
	},
	{
		name: "Dawn Wings Necrozma",
		id: "dawn wings necrozma",
		type1: "Psychic",
		type2: "Ghost",
	},
	{
		name: "Ultra Necrozma",
		id: "ultra necrozma",
		type1: "Psychic",
		type2: "Dragon",
	},
	{ name: "Magearna", id: "magearna", type1: "Steel", type2: "Fairy" },
	{
		name: "Original Color Magearna",
		id: "original color magearna",
		type1: "Steel",
		type2: "Fairy",
	},
	{ name: "Marshadow", id: "marshadow", type1: "Fighting", type2: "Ghost" },
	{
		name: "Poipole [Adhesive]",
		id: "poipole [adhesive]",
		type1: "Poison",
		type2: "",
	},
	{ name: "Poipole", id: "poipole", type1: "Poison", type2: "" },
	{
		name: "Naganadel [Stinger]",
		id: "naganadel [stinger]",
		type1: "Poison",
		type2: "Dragon",
	},
	{ name: "Naganadel", id: "naganadel", type1: "Poison", type2: "Dragon" },
	{
		name: "Stakataka [Assembly]",
		id: "stakataka [assembly]",
		type1: "Rock",
		type2: "Steel",
	},
	{ name: "Stakataka", id: "stakataka", type1: "Rock", type2: "Steel" },
	{
		name: "Blacephalon [Burst]",
		id: "blacephalon [burst]",
		type1: "Fire",
		type2: "Ghost",
	},
	{ name: "Blacephalon", id: "blacephalon", type1: "Fire", type2: "Ghost" },
	{ name: "Zeraora", id: "zeraora", type1: "Electric", type2: "" },
	{ name: "Meltan", id: "meltan", type1: "Steel", type2: "" },
	{ name: "Melmetal", id: "melmetal", type1: "Steel", type2: "" },
	{
		name: "Gigantamax Melmetal",
		id: "gigantamax melmetal",
		type1: "Steel",
		type2: "",
	},
	{ name: "Grookey", id: "grookey", type1: "Grass", type2: "" },
	{ name: "Thwackey", id: "thwackey", type1: "Grass", type2: "" },
	{ name: "Rillaboom", id: "rillaboom", type1: "Grass", type2: "" },
	{
		name: "Gigantamax Rillaboom",
		id: "gigantamax rillaboom",
		type1: "Grass",
		type2: "",
	},
	{ name: "Scorbunny", id: "scorbunny", type1: "Fire", type2: "" },
	{ name: "Raboot", id: "raboot", type1: "Fire", type2: "" },
	{ name: "Cinderace", id: "cinderace", type1: "Fire", type2: "" },
	{
		name: "Gigantamax Cinderace",
		id: "gigantamax cinderace",
		type1: "Fire",
		type2: "",
	},
	{ name: "Sobble", id: "sobble", type1: "Water", type2: "" },
	{ name: "Drizzile", id: "drizzile", type1: "Water", type2: "" },
	{ name: "Inteleon", id: "inteleon", type1: "Water", type2: "" },
	{
		name: "Gigantamax Inteleon",
		id: "gigantamax inteleon",
		type1: "Water",
		type2: "",
	},
	{ name: "Skwovet", id: "skwovet", type1: "Normal", type2: "" },
	{ name: "Greedent", id: "greedent", type1: "Normal", type2: "" },
	{ name: "Rookidee", id: "rookidee", type1: "Flying", type2: "" },
	{ name: "Corvisquire", id: "corvisquire", type1: "Flying", type2: "" },
	{ name: "Corviknight", id: "corviknight", type1: "Flying", type2: "Steel" },
	{
		name: "Gigantamax Corviknight",
		id: "gigantamax corviknight",
		type1: "Flying",
		type2: "Steel",
	},
	{ name: "Blipbug", id: "blipbug", type1: "Bug", type2: "" },
	{ name: "Dottler", id: "dottler", type1: "Bug", type2: "Psychic" },
	{ name: "Orbeetle", id: "orbeetle", type1: "Bug", type2: "Psychic" },
	{
		name: "Gigantamax Orbeetle",
		id: "gigantamax orbeetle",
		type1: "Bug",
		type2: "Psychic",
	},
	{ name: "Nickit", id: "nickit", type1: "Dark", type2: "" },
	{ name: "Thievul", id: "thievul", type1: "Dark", type2: "" },
	{ name: "Gossifleur", id: "gossifleur", type1: "Grass", type2: "" },
	{ name: "Eldegoss", id: "eldegoss", type1: "Grass", type2: "" },
	{ name: "Wooloo", id: "wooloo", type1: "Normal", type2: "" },
	{ name: "Dubwool", id: "dubwool", type1: "Normal", type2: "" },
	{ name: "Chewtle", id: "chewtle", type1: "Water", type2: "" },
	{ name: "Drednaw", id: "drednaw", type1: "Water", type2: "Rock" },
	{
		name: "Gigantamax Drednaw",
		id: "gigantamax drednaw",
		type1: "Water",
		type2: "Rock",
	},
	{ name: "Yamper", id: "yamper", type1: "Electric", type2: "" },
	{ name: "Boltund", id: "boltund", type1: "Electric", type2: "" },
	{ name: "Rolycoly", id: "rolycoly", type1: "Rock", type2: "" },
	{ name: "Carkol", id: "carkol", type1: "Rock", type2: "Fire" },
	{ name: "Coalossal", id: "coalossal", type1: "Rock", type2: "Fire" },
	{
		name: "Gigantamax Coalossal",
		id: "gigantamax coalossal",
		type1: "Rock",
		type2: "Fire",
	},
	{ name: "Applin", id: "applin", type1: "Grass", type2: "Dragon" },
	{ name: "Flapple", id: "flapple", type1: "Grass", type2: "Dragon" },
	{
		name: "Gigantamax Flapple",
		id: "gigantamax flapple",
		type1: "Grass",
		type2: "Dragon",
	},
	{ name: "Appletun", id: "appletun", type1: "Grass", type2: "Dragon" },
	{
		name: "Gigantamax Appletun",
		id: "gigantamax appletun",
		type1: "Grass",
		type2: "Dragon",
	},
	{ name: "Silicobra", id: "silicobra", type1: "Ground", type2: "" },
	{ name: "Sandaconda", id: "sandaconda", type1: "Ground", type2: "" },
	{
		name: "Gigantamax Sandaconda",
		id: "gigantamax sandaconda",
		type1: "Ground",
		type2: "",
	},
	{ name: "Cramorant", id: "cramorant", type1: "Flying", type2: "Water" },
	{
		name: "Cramorant Gulping Form",
		id: "cramorant gulping form",
		type1: "Flying",
		type2: "Water",
	},
	{
		name: "Cramorant Gorging Form",
		id: "cramorant gorging form",
		type1: "Flying",
		type2: "Water",
	},
	{ name: "Arrokuda", id: "arrokuda", type1: "Water", type2: "" },
	{ name: "Barraskewda", id: "barraskewda", type1: "Water", type2: "" },
	{ name: "Toxel", id: "toxel", type1: "Electric", type2: "Poison" },
	{
		name: "Toxtricity Amped",
		id: "toxtricity amped",
		type1: "Electric",
		type2: "Poison",
	},
	{ name: "Toxtricity", id: "toxtricity", type1: "Electric", type2: "Poison" },
	{
		name: "Toxtricity Low Key",
		id: "toxtricity low key",
		type1: "Electric",
		type2: "Poison",
	},
	{
		name: "Gigantamax Toxtricity",
		id: "gigantamax toxtricity",
		type1: "Electric",
		type2: "Poison",
	},
	{ name: "Sizzlipede", id: "sizzlipede", type1: "Fire", type2: "Bug" },
	{ name: "Centiskorch", id: "centiskorch", type1: "Fire", type2: "Bug" },
	{
		name: "Gigantamax Centiskorch",
		id: "gigantamax centiskorch",
		type1: "Fire",
		type2: "Bug",
	},
	{ name: "Clobbopus", id: "clobbopus", type1: "Fighting", type2: "" },
	{ name: "Grapploct", id: "grapploct", type1: "Fighting", type2: "" },
	{ name: "Sinistea Phony", id: "sinistea phony", type1: "Ghost", type2: "" },
	{
		name: "Sinistea Antique",
		id: "sinistea antique",
		type1: "Ghost",
		type2: "",
	},
	{
		name: "Polteageist Phony",
		id: "polteageist phony",
		type1: "Ghost",
		type2: "",
	},
	{
		name: "Polteageist Antique",
		id: "polteageist antique",
		type1: "Ghost",
		type2: "",
	},
	{ name: "Hatenna", id: "hatenna", type1: "Psychic", type2: "" },
	{ name: "Hattrem", id: "hattrem", type1: "Psychic", type2: "" },
	{ name: "Hatterene", id: "hatterene", type1: "Psychic", type2: "Fairy" },
	{
		name: "Gigantamax Hatterene",
		id: "gigantamax hatterene",
		type1: "Psychic",
		type2: "Fairy",
	},
	{ name: "Impidimp", id: "impidimp", type1: "Dark", type2: "Fairy" },
	{ name: "Morgrem", id: "morgrem", type1: "Dark", type2: "Fairy" },
	{ name: "Grimmsnarl", id: "grimmsnarl", type1: "Dark", type2: "Fairy" },
	{
		name: "Gigantamax Grimmsnarl",
		id: "gigantamax grimmsnarl",
		type1: "Dark",
		type2: "Fairy",
	},
	{ name: "Obstagoon", id: "obstagoon", type1: "Dark", type2: "Normal" },
	{ name: "Perrserker", id: "perrserker", type1: "Steel", type2: "" },
	{ name: "Cursola", id: "cursola", type1: "Ghost", type2: "" },
	{ name: "Sirfetch'd", id: "sirfetchd", type1: "Fighting", type2: "" },
	{ name: "Mr. Rime", id: "mrrime", type1: "Ice", type2: "Psychic" },
	{ name: "Runerigus", id: "runerigus", type1: "Ground", type2: "Ghost" },
	{ name: "Milcery", id: "milcery", type1: "Fairy", type2: "" },
	{
		name: "Alcremie Vanilla Cream",
		id: "alcremie vanilla cream",
		type1: "Fairy",
		type2: "",
	},
	{
		name: "Alcremie Ruby Cream",
		id: "alcremie ruby cream",
		type1: "Fairy",
		type2: "",
	},
	{
		name: "Alcremie Matcha Cream",
		id: "alcremie matcha cream",
		type1: "Fairy",
		type2: "",
	},
	{
		name: "Alcremie Mint Cream",
		id: "alcremie mint cream",
		type1: "Fairy",
		type2: "",
	},
	{
		name: "Alcremie Lemon Cream",
		id: "alcremie lemon cream",
		type1: "Fairy",
		type2: "",
	},
	{
		name: "Alcremie Salted Cream",
		id: "alcremie salted cream",
		type1: "Fairy",
		type2: "",
	},
	{
		name: "Alcremie Ruby Swirl",
		id: "alcremie ruby swirl",
		type1: "Fairy",
		type2: "",
	},
	{
		name: "Alcremie Caramel Swirl",
		id: "alcremie caramel swirl",
		type1: "Fairy",
		type2: "",
	},
	{
		name: "Alcremie Rainbow Swirl",
		id: "alcremie rainbow swirl",
		type1: "Fairy",
		type2: "",
	},
	{
		name: "Gigantamax Alcremie",
		id: "gigantamax alcremie",
		type1: "Fairy",
		type2: "",
	},
	{ name: "Falinks", id: "falinks", type1: "Fighting", type2: "" },
	{ name: "Pincurchin", id: "pincurchin", type1: "Electric", type2: "" },
	{ name: "Snom", id: "snom", type1: "Ice", type2: "Bug" },
	{ name: "Frosmoth", id: "frosmoth", type1: "Ice", type2: "Bug" },
	{ name: "Stonjourner", id: "stonjourner", type1: "Rock", type2: "" },
	{ name: "Eiscue Ice Face", id: "eiscue ice face", type1: "Ice", type2: "" },
	{
		name: "Eiscue Noice Face",
		id: "eiscue noice face",
		type1: "Ice",
		type2: "",
	},
	{
		name: "Indeedee Male",
		id: "indeedee male",
		type1: "Psychic",
		type2: "Normal",
	},
	{
		name: "Indeedee Female",
		id: "indeedee female",
		type1: "Psychic",
		type2: "Normal",
	},
	{
		name: "Morpeko Full Belly",
		id: "morpeko full belly",
		type1: "Electric",
		type2: "Dark",
	},
	{
		name: "Morpeko Hangry",
		id: "morpeko hangry",
		type1: "Electric",
		type2: "Dark",
	},
	{ name: "Cufant", id: "cufant", type1: "Steel", type2: "" },
	{ name: "Copperajah", id: "copperajah", type1: "Steel", type2: "" },
	{
		name: "Gigantamax Copperajah",
		id: "gigantamax copperajah",
		type1: "Steel",
		type2: "",
	},
	{ name: "Dracozolt", id: "dracozolt", type1: "Electric", type2: "Dragon" },
	{ name: "Arctozolt", id: "arctozolt", type1: "Electric", type2: "Ice" },
	{ name: "Dracovish", id: "dracovish", type1: "Water", type2: "Dragon" },
	{ name: "Arctovish", id: "arctovish", type1: "Water", type2: "Ice" },
	{ name: "Duraludon", id: "duraludon", type1: "Steel", type2: "Dragon" },
	{
		name: "Gigantamax Duraludon",
		id: "gigantamax duraludon",
		type1: "Steel",
		type2: "Dragon",
	},
	{ name: "Dreepy", id: "dreepy", type1: "Dragon", type2: "Ghost" },
	{ name: "Drakloak", id: "drakloak", type1: "Dragon", type2: "Ghost" },
	{ name: "Dragapult", id: "dragapult", type1: "Dragon", type2: "Ghost" },
	{
		name: "Zacian Hero of Many Battles",
		id: "zacian hero of many battles",
		type1: "Fairy",
		type2: "",
	},
	{
		name: "Zacian Crowned Sword",
		id: "zacian crowned sword",
		type1: "Fairy",
		type2: "Steel",
	},
	{
		name: "Zamazenta Hero of Many Battles",
		id: "zamazenta hero of many battles",
		type1: "Fighting",
		type2: "",
	},
	{
		name: "Zamazenta Crowned Shield",
		id: "zamazenta crowned shield",
		type1: "Fighting",
		type2: "Steel",
	},
	{ name: "Eternatus", id: "eternatus", type1: "Poison", type2: "Dragon" },
	{
		name: "Eternatus Eternamax",
		id: "eternatus eternamax",
		type1: "Poison",
		type2: "Dragon",
	},
	{ name: "Kubfu", id: "kubfu", type1: "Fighting", type2: "" },
	{
		name: "Urshifu Single Strike Style",
		id: "urshifu single strike style",
		type1: "Fighting",
		type2: "Dark",
	},
	{
		name: "Urshifu Rapid Strike Style",
		id: "urshifu rapid strike style",
		type1: "Fighting",
		type2: "Water",
	},
	{
		name: "Gigantamax Urshifu (SS)",
		id: "gigantamax urshifu (ss)",
		type1: "Fighting",
		type2: "Dark",
	},
	{
		name: "Gigantamax Urshifu (RS)",
		id: "gigantamax urshifu (rs)",
		type1: "Fighting",
		type2: "Water",
	},
	{ name: "Zarude", id: "zarude", type1: "Dark", type2: "Grass" },
	{ name: "Zarude Dada", id: "zarude dada", type1: "Dark", type2: "Grass" },
	{ name: "Regieleki", id: "regieleki", type1: "Electric", type2: "" },
	{ name: "Regidrago", id: "regidrago", type1: "Dragon", type2: "" },
	{ name: "Glastrier", id: "glastrier", type1: "Ice", type2: "" },
	{ name: "Spectrier", id: "spectrier", type1: "Ghost", type2: "" },
	{ name: "Calyrex", id: "calyrex", type1: "Psychic", type2: "Grass" },
	{
		name: "Ice Rider Calyrex",
		id: "ice rider calyrex",
		type1: "Psychic",
		type2: "Ice",
	},
	{
		name: "Shadow Rider Calyrex",
		id: "shadow rider calyrex",
		type1: "Psychic",
		type2: "Ghost",
	},
];
