let people = [
	{
		fname: "",
		gname: "",
		id: "akiyama_dad",
		gender: "male",
		partners: "",
		mid: "",
		fid: "",
		onlineImg: "",
		localImg: "",
		bday: "",
		bmonth: "",
		byear: "",
		dday: "",
		dmonth: "",
		dyear: "",
	},
	{
		fname: "Akiyama",
		gname: "Kōyō",
		id: "akiyama_koyo",
		gender: "male",
		partners: "hinata_kaho",
		mid: "",
		fid: "akiyama_dad",
		onlineImg:
			"https://ih0.redbubble.net/image.494702694.6668/flat,800x800,075,f.u1.jpg",
		localImg: "akizuki_koyo",
		bday: "4",
		bmonth: "4",
		byear: "1999",
		dday: "",
		dmonth: "",
		dyear: "",
	},
	{
		fname: "Akiyama",
		gname: "Mio",
		id: "akiyama_mio",
		gender: "female",
		partners: "tainaka_ritsu",
		mid: "",
		fid: "akiyama_dad",
		onlineImg: "https://wallpapercave.com/wp/wp3137114.jpg",
		localImg: "akiyama_mio",
		bday: "15",
		bmonth: "1",
		byear: "2004",
		dday: "",
		dmonth: "",
		dyear: "",
	},
	{
		fname: "Akiyama",
		gname: "Maya",
		id: "akiyama_maya",
		gender: "female",
		partners: "",
		mid: "",
		fid: "akiyama_dad",
		onlineImg:
			"https://vignette.wikia.nocookie.net/gochiusa/images/0/09/Maya.png/revision/latest?cb=20180102122052",
		localImg: "joga_maya",
		bday: "8",
		bmonth: "8",
		byear: "2007",
		dday: "",
		dmonth: "",
		dyear: "",
	},
	{
		fname: "Akiyama",
		gname: "Megumi",
		id: "akiyama_megumi",
		gender: "female",
		partners: "",
		mid: "",
		fid: "akiyama_dad",
		onlineImg:
			"https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.nautiljon.com%2Fimages%2Fperso%2F00%2F89%2Fnatsu_megumi_17398.jpg&f=1&nofb=1",
		localImg: "natsu_megumi",
		bday: "8",
		bmonth: "8",
		byear: "2007",
		dday: "",
		dmonth: "",
		dyear: "",
	},
	{
		fname: "Hinata",
		gname: "Kaho",
		id: "hinata_kaho",
		gender: "female",
		partners: "akiyama_koyo",
		mid: "himesaka_emily",
		fid: "hinata_dad",
		onlineImg:
			"https://i.pinimg.com/736x/f3/c0/39/f3c039a49f2c943cbe296bed06afe319.jpg",
		localImg: "hinata_kaho",
		bday: "12",
		bmonth: "8",
		byear: "2003",
		dday: "",
		dmonth: "",
		dyear: "",
	},
	{
		fname: "",
		gname: "",
		id: "hinata_dad",
		gender: "",
		partners: "himesaka_emily",
		mid: "",
		fid: "",
		onlineImg: "",
		localImg: "",
		bday: "",
		bmonth: "",
		byear: "",
		dday: "",
		dmonth: "",
		dyear: "",
	},
	{
		fname: "Hinata",
		gname: "Noa",
		id: "hinata_noa",
		gender: "female",
		partners: "hoshino_hinata",
		mid: "himesaka_emily",
		fid: "hinata_dad",
		onlineImg:
			"https://i.pinimg.com/originals/41/15/d9/4115d95b09adb6ec9a985181e152101c.jpg",
		localImg: "himesaka_noa",
		bday: "24",
		bmonth: "11",
		byear: "2009",
		dday: "",
		dmonth: "",
		dyear: "",
	},
	{
		fname: "Himesaka",
		gname: "Emily",
		id: "himesaka_emily",
		gender: "female",
		partners: "hinata_dad",
		mid: "",
		fid: "himesaka_parent",
		onlineImg:
			"https://i.pinimg.com/236x/e7/89/6d/e7896d6fc0765d37f4662c5a0b3e5d13.jpg?nii=t",
		localImg: "himesaka_emily",
		bday: "",
		bmonth: "",
		byear: "1984",
		dday: "",
		dmonth: "",
		dyear: "",
	},
	{
		fname: "Tainaka",
		gname: "Ritsu",
		id: "tainaka_ritsu",
		gender: "female",
		partners: "akiyama_mio",
		mid: "",
		fid: "tainaka_parent",
		onlineImg: "https://s1.zerochan.net/Tainaka.Ritsu.600.715682.jpg",
		localImg: "tainaka_ritsu",
		bday: "21",
		bmonth: "8",
		byear: "2003",
		dday: "",
		dmonth: "",
		dyear: "",
	},
	{
		fname: "Tainaka",
		gname: "Satoshi",
		id: "tainaka_satoshi",
		gender: "male",
		partners: "",
		mid: "",
		fid: "tainaka_parent",
		onlineImg: "https://www.postavy.cz/foto/satoshi-tainaka-foto.jpg",
		localImg: "tainaka_satoshi",
		bday: "",
		bmonth: "",
		byear: "2005",
		dday: "",
		dmonth: "",
		dyear: "",
	},
	{
		fname: "",
		gname: "",
		id: "tainaka_parent",
		gender: "",
		partners: "",
		mid: "chiyas_grandma",
		fid: "",
		onlineImg: "",
		localImg: "",
		bday: "",
		bmonth: "",
		byear: "",
		dday: "",
		dmonth: "",
		dyear: "",
	},
	{
		fname: "",
		gname: "",
		id: "chiyas_grandma",
		gender: "female",
		partners: "",
		mid: "",
		fid: "",
		onlineImg:
			"https://www.anime-planet.com/images/characters/thumbs/chiyas-grandmother-92677.jpg?t=1450034260",
		localImg: "chiyas_grandma",
		bday: "",
		bmonth: "",
		byear: "",
		dday: "",
		dmonth: "",
		dyear: "",
	},
	{
		fname: "",
		gname: "",
		id: "ujimatsu_parent",
		gender: "",
		partners: "",
		mid: "chiyas_grandma",
		fid: "",
		onlineImg: "",
		localImg: "",
		bday: "",
		bmonth: "",
		byear: "",
		dday: "",
		dmonth: "",
		dyear: "",
	},
	{
		fname: "Ujimatsu",
		gname: "Chiya",
		id: "ujimatsu_chiya",
		gender: "female",
		partners: "hoto_cocoa",
		mid: "",
		fid: "ujimatsu_parent",
		onlineImg:
			"https://pa1.narvii.com/6607/fc72a5a6973da1224f5c437c1163e691d10f66ec_hq.gif",
		localImg: "ujimatsu_chiya",
		bday: "19",
		bmonth: "9",
		byear: "2005",
		dday: "",
		dmonth: "",
		dyear: "",
	},
	{
		fname: "",
		gname: "",
		id: "karasuma_parent",
		gender: "",
		partners: "",
		mid: "chiyas_grandma",
		fid: "",
		onlineImg: "",
		localImg: "",
		bday: "",
		bmonth: "",
		byear: "",
		dday: "",
		dmonth: "",
		dyear: "",
	},
	{
		fname: "Karasuma",
		gname: "Sakura",
		id: "karasuma_sakura",
		gender: "female",
		partners: "kuzehashi_akari",
		mid: "",
		fid: "karasuma_parent",
		onlineImg:
			"https://www.anime-planet.com/images/characters/sakura-karasuma-64012.jpg?t=1492921947",
		localImg: "karasuma_sakura",
		bday: "19",
		bmonth: "10",
		byear: "1997",
		dday: "",
		dmonth: "",
		dyear: "",
	},
	{
		fname: "Kuzehashi",
		gname: "Akari",
		id: "kuzehashi_akari",
		gender: "female",
		partners: "karasuma_sakura",
		mid: "",
		fid: "kuzehashi_parent",
		onlineImg: "https://waifu.wiki/images/thumb/5/5c/3040.png/600px-3040.png",
		localImg: "kuzehashi_akari",
		bday: "24",
		bmonth: "4",
		byear: "1998",
		dday: "",
		dmonth: "",
		dyear: "",
	},
	{
		fname: "",
		gname: "",
		id: "kuzehashi_parent",
		gender: "",
		partners: "",
		mid: "",
		fid: "",
		onlineImg: "",
		localImg: "",
		bday: "",
		bmonth: "",
		byear: "",
		dday: "",
		dmonth: "",
		dyear: "",
	},
	{
		fname: "Kuzehashi",
		gname: "Ruki",
		id: "kuzehashi_ruki",
		gender: "female",
		partners: "",
		mid: "",
		fid: "kuzehashi_parent",
		onlineImg:
			"https://64.media.tumblr.com/c6ccfde1a8412ed25a5f3b424f10bcf6/tumblr_prt3twAw1S1tckkcf_1280.jpg",
		localImg: "irokawa_ruki",
		bday: "24",
		bmonth: "12",
		byear: "2005",
		dday: "",
		dmonth: "",
		dyear: "",
	},
	{
		fname: "Hoshino",
		gname: "Hinata",
		id: "hoshino_hinata",
		gender: "female",
		partners: "hinata_noa",
		mid: "hoshino_chizuru",
		fid: "",
		onlineImg:
			"https://i.pinimg.com/originals/09/9c/b7/099cb751742164865fb1faece034fa12.jpg",
		localImg: "hoshino_hinata",
		bday: "10",
		bmonth: "5",
		byear: "2009",
		dday: "",
		dmonth: "",
		dyear: "",
	},
	{
		fname: "Hoshino",
		gname: "Miyako",
		id: "hoshino_miyako",
		gender: "female",
		partners: "matsumoto_koko",
		mid: "hoshino_chizuru",
		fid: "",
		onlineImg:
			"https://i.pinimg.com/originals/0d/c7/b9/0dc7b9f97d64c8bfe51c3e180af65102.jpg",
		localImg: "hoshino_miyako",
		bday: "9",
		bmonth: "9",
		byear: "2002",
		dday: "",
		dmonth: "",
		dyear: "",
	},
	{
		fname: "Hoshino",
		gname: "Chizuru",
		id: "hoshino_chizuru",
		gender: "female",
		partners: "",
		mid: "",
		fid: "",
		onlineImg:
			"https://ami.animecharactersdatabase.com/uploads/chars/1-1565288606.png",
		localImg: "hoshino_chizuru",
		bday: "18",
		bmonth: "1",
		byear: "1981",
		dday: "",
		dmonth: "",
		dyear: "",
	},
	{
		fname: "Matsumoto",
		gname: "Hinata",
		id: "matsumo_hina",
		gender: "female",
		partners: "",
		mid: "",
		fid: "matsumoto_parent",
		onlineImg: "https://cdn.myanimelist.net/images/characters/6/434332.jpg",
		localImg: "fa",
		bday: "12",
		bmonth: "2",
		byear: "1997",
		dday: "",
		dmonth: "",
		dyear: "",
	},
	{
		fname: "Matsumoto",
		gname: "Kōko",
		id: "matsumoto_koko",
		gender: "female",
		partners: "hoshino_miyako",
		mid: "",
		fid: "matsumoto_parent",
		onlineImg:
			"https://static.tvtropes.org/pmwiki/pub/images/tumblr_pmtxsl2pts1u86t2qo1_400.jpg",
		localImg: "matsumoto_koko",
		bday: "16",
		bmonth: "10",
		byear: "2002",
		dday: "",
		dmonth: "",
		dyear: "",
	},
	{
		fname: "Matsumoto",
		gname: "Rise",
		id: "matsumoto_rise",
		gender: "female",
		partners: "",
		mid: "",
		fid: "matsumoto_parent",
		onlineImg:
			"https://pa1.narvii.com/6554/3f60d92d93380e33ef45ecfe425f702634f0db7f_hq.gif",
		localImg: "matsumoto_rise",
		bday: "23",
		bmonth: "5",
		byear: "2005",
		dday: "",
		dmonth: "",
		dyear: "",
	},
	{
		fname: "Matsumoto",
		gname: "Yūna",
		id: "matsumoto_yuna",
		gender: "female",
		partners: "",
		mid: "",
		fid: "matsumoto_parent",
		onlineImg: "https://i.ytimg.com/vi/4y-iFgrbPok/maxresdefault.jpg",
		localImg: "matsumoto_yuna",
		bday: "5",
		bmonth: "3",
		byear: "2015",
		dday: "",
		dmonth: "",
		dyear: "",
	},
	{
		fname: "",
		gname: "",
		id: "matsumoto_parent",
		gender: "",
		partners: "",
		mid: "",
		fid: "",
		onlineImg: "",
		localImg: "",
		bday: "",
		bmonth: "",
		byear: "",
		dday: "",
		dmonth: "",
		dyear: "",
	},
	{
		fname: "",
		gname: "",
		id: "hirasawa_mom",
		gender: "female",
		partners: "hirasawa_dad",
		mid: "",
		fid: "himesaka_parent",
		onlineImg:
			"https://i.pinimg.com/originals/32/ea/8f/32ea8fdd6cbe5fffee5d995df352d9d4.png",
		localImg: "yuis_and_uis_mother",
		bday: "",
		bmonth: "",
		byear: "",
		dday: "",
		dmonth: "",
		dyear: "",
	},
	{
		fname: "",
		gname: "",
		id: "hirasawa_dad",
		gender: "male",
		partners: "hirasawa_mom",
		mid: "",
		fid: "",
		onlineImg: "",
		localImg: "yuis_and_uis_father",
		bday: "",
		bmonth: "",
		byear: "",
		dday: "",
		dmonth: "",
		dyear: "",
	},
	{
		fname: "",
		gname: "",
		id: "himesaka_parent",
		gender: "",
		partners: "",
		mid: "",
		fid: "",
		onlineImg: "",
		localImg: "",
		bday: "",
		bmonth: "",
		byear: "",
		dday: "",
		dmonth: "",
		dyear: "",
	},
	{
		fname: "Hirasawa",
		gname: "Yui",
		id: "hirasawa_yui",
		gender: "female",
		partners: "nakano_azusa",
		mid: "hirasawa_mom",
		fid: "hirasawa_dad",
		onlineImg:
			"http://images4.fanpop.com/image/photos/16500000/Yui-Hirasawa-yui-hirasawa-16561913-1280-1024.jpg",
		localImg: "hirasawa_yui",
		bday: "27",
		bmonth: "11",
		byear: "2003",
		dday: "",
		dmonth: "",
		dyear: "",
	},
	{
		fname: "Hirasawa",
		gname: "Ui",
		id: "hirasawa_ui",
		gender: "female",
		partners: "suzuki_jun",
		mid: "hirasawa_mom",
		fid: "hirasawa_dad",
		onlineImg:
			"https://i.pinimg.com/736x/8b/e0/81/8be0815a652fdd4e878d96859d27767a.jpg",
		localImg: "hirasawa_ui",
		bday: "22",
		bmonth: "2",
		byear: "2005",
		dday: "",
		dmonth: "",
		dyear: "",
	},
	{
		fname: "Hirasawa",
		gname: "Chitose",
		id: "hirasawa_chitose",
		gender: "female",
		partners: "",
		mid: "hirasawa_mom",
		fid: "hirasawa_dad",
		onlineImg:
			"https://www.anime-planet.com/images/characters/chitose-ikeda-27517.jpg",
		localImg: "ikeda_chitose",
		bday: "10",
		bmonth: "3",
		byear: "2006",
		dday: "",
		dmonth: "",
		dyear: "",
	},
	{
		fname: "Hirasawa",
		gname: "Chizuru",
		id: "hirasawa_chizuru",
		gender: "female",
		partners: "",
		mid: "hirasawa_mom",
		fid: "hirasawa_dad",
		onlineImg:
			"https://pm1.narvii.com/6547/7d088bfd998c101aeea58bd4a6b7cda33042e1c2_hq.jpg",
		localImg: "ikeda_chizuru",
		bday: "10",
		bmonth: "3",
		byear: "2006",
		dday: "",
		dmonth: "",
		dyear: "",
	},
	{
		fname: "Nakano",
		gname: "Azusa",
		id: "nakano_azusa",
		gender: "female",
		partners: "hirasawa_yui",
		mid: "",
		fid: "",
		onlineImg:
			"https://yt3.ggpht.com/a/AATXAJzxozkF5h8iA4575nDe33tDUiv-0K2veSw4Zw=s900-c-k-c0xffffffff-no-rj-mo",
		localImg: "nakano_azusa",
		bday: "11",
		bmonth: "11",
		byear: "2004",
		dday: "",
		dmonth: "",
		dyear: "",
	},
	{
		fname: "Suzuki",
		gname: "Jun",
		id: "suzuki_jun",
		gender: "female",
		partners: "hirasawa_ui",
		mid: "",
		fid: "suzuki_parent",
		onlineImg:
			"https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fstatici.behindthevoiceactors.com%2Fbehindthevoiceactors%2F_img%2Fchars%2Fjun-suzuki-k-on-9.1.jpg&f=1&nofb=1",
		localImg: "suzuki_jun",
		bday: "8",
		bmonth: "4",
		byear: "2004",
		dday: "",
		dmonth: "",
		dyear: "",
	},
	{
		fname: "",
		gname: "",
		id: "suzuki_parent",
		gender: "",
		partners: "",
		mid: "",
		fid: "",
		onlineImg: "",
		localImg: "",
		bday: "",
		bmonth: "",
		byear: "",
		dday: "",
		dmonth: "",
		dyear: "",
	},
	{
		fname: "Suzuki",
		gname: "Hajime",
		id: "suzuki_hajime",
		gender: "male",
		partners: "",
		mid: "",
		fid: "suzuki_parent",
		onlineImg:
			"https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fstatici.behindthevoiceactors.com%2Fbehindthevoiceactors%2F_img%2Fchars%2Fsuzuki-bakuman-42.2.jpg&f=1&nofb=1",
		localImg: "suzuki_hajime",
		bday: "",
		bmonth: "",
		byear: "1994",
		dday: "",
		dmonth: "",
		dyear: "",
	},
	{
		fname: "Mashiro",
		gname: "Moritaka",
		id: "mashiro_moritaka",
		gender: "male",
		partners: "azuki_miho",
		mid: "mashiro_kayoko",
		fid: "mashiro_masahiro",
		onlineImg:
			"http://ami.animecharactersdatabase.com/images/2496/Moritaka_Mashiro.jpg",
		localImg: "mashiro_moritaka",
		bday: "18",
		bmonth: "2",
		byear: "1994",
		dday: "",
		dmonth: "",
		dyear: "",
	},
	{
		fname: "Mashiro",
		gname: "Kayoko",
		id: "mashiro_kayoko",
		gender: "female",
		partners: "mashiro_masahiro",
		mid: "",
		fid: "",
		onlineImg: "https://64.media.tumblr.com/tumblr_lsyyndsiDy1qi70w1o1_400.jpg",
		localImg: "mashiro_kayoko",
		bday: "",
		bmonth: "",
		byear: "",
		dday: "",
		dmonth: "",
		dyear: "",
	},
	{
		fname: "Mashiro",
		gname: "Masahiro",
		id: "mashiro_masahiro",
		gender: "male",
		partners: "mashiro_kayoko",
		mid: "",
		fid: "mashiro_fumi",
		onlineImg:
			"https://yt3.ggpht.com/a/AATXAJzM_PnJMktMpJCep8hzB-T40TgV-3E11M8fkg=s900-c-k-c0xffffffff-no-rj-mo",
		localImg: "mashiro_masahiro",
		bday: "3",
		bmonth: "8",
		byear: "1970",
		dday: "",
		dmonth: "",
		dyear: "",
	},
	{
		fname: "Mashiro",
		gname: "Fumi",
		id: "mashiro_fumi",
		gender: "male",
		partners: "",
		mid: "",
		fid: "",
		onlineImg:
			"https://s4.anilist.co/file/anilistcdn/character/large/b37582-Fb3BtshWduiA.png",
		localImg: "mashiro_fumi",
		bday: "",
		bmonth: "",
		byear: "",
		dday: "",
		dmonth: "",
		dyear: "",
	},
	{
		fname: "Mashiro",
		gname: "Nobuhiro",
		id: "mashiro_nobuhiro",
		gender: "male",
		partners: "",
		mid: "",
		fid: "mashiro_fumi",
		onlineImg:
			"http://ftpmirror.your.org/pub/wikimedia/images/wikipedia/pt/e/e1/Mashiro_Nobuhiro.jpg",
		localImg: "mashiro_nobuhiro",
		bday: "",
		bmonth: "",
		byear: "1962",
		dday: "",
		dmonth: "",
		dyear: "2006",
	},
	{
		fname: "Azuki",
		gname: "Miho",
		id: "azuki_miho",
		gender: "female",
		partners: "mashiro_moritaka",
		mid: "haruno_miyuki",
		fid: "",
		onlineImg:
			"https://2.bp.blogspot.com/-R7hsROBhhGA/TZpCP16kKPI/AAAAAAAAAV8/UOpEALONTyY/s1600/Miho+Azuki.jpg",
		localImg: "azuki_miho",
		bday: "5",
		bmonth: "11",
		byear: "1993",
		dday: "",
		dmonth: "",
		dyear: "",
	},
	{
		fname: "Azuki",
		gname: "Mina",
		id: "azuki_mina",
		gender: "female",
		partners: "",
		mid: "haruno_miyuki",
		fid: "",
		onlineImg:
			"https://cdn.anisearch.de/images/character/cover/full/18/18488.jpg",
		localImg: "azuki_mina",
		bday: "",
		bmonth: "",
		byear: "1999",
		dday: "",
		dmonth: "",
		dyear: "",
	},
	{
		fname: "Haruno",
		gname: "Miyuki",
		id: "haruno_miyuki",
		gender: "female",
		partners: "",
		mid: "",
		fid: "haruno_parent",
		onlineImg:
			"https://thicc.mywaifulist.moe/waifus/7661/b33d9c7a85df8fd6428b4bba51cd817af919461ecd172d39bdb06d4e2e4a4bed_thumb.jpeg",
		localImg: "haruno_miyuki",
		bday: "",
		bmonth: "",
		byear: "1963",
		dday: "",
		dmonth: "",
		dyear: "",
	},
	{
		fname: "",
		gname: "",
		id: "haruno_parent",
		gender: "",
		partners: "",
		mid: "",
		fid: "",
		onlineImg: "",
		localImg: "",
		bday: "",
		bmonth: "",
		byear: "",
		dday: "",
		dmonth: "",
		dyear: "",
	},
	{
		fname: "",
		gname: "",
		id: "himes_parent",
		gender: "",
		partners: "",
		mid: "",
		fid: "haruno_parent",
		onlineImg: "",
		localImg: "",
		bday: "",
		bmonth: "",
		byear: "",
		dday: "",
		dmonth: "",
		dyear: "",
	},
	{
		fname: "Haruno",
		gname: "Hime",
		id: "haruno_hime",
		gender: "female",
		partners: "",
		mid: "",
		fid: "himes_parent",
		onlineImg:
			"https://1.bp.blogspot.com/-8ctzJMuOWlw/U6wu3P-exSI/AAAAAAAAAi8/aFDHVrJGAGQ/s1600/hime.png",
		localImg: "haruno_hime",
		bday: "12",
		bmonth: "5",
		byear: "2006",
		dday: "",
		dmonth: "",
		dyear: "",
	},
	{
		fname: "",
		gname: "",
		id: "aoyamas_parent",
		gender: "",
		partners: "",
		mid: "",
		fid: "haruno_parent",
		onlineImg: "",
		localImg: "",
		bday: "",
		bmonth: "",
		byear: "",
		dday: "",
		dmonth: "",
		dyear: "",
	},
	{
		fname: "Aoyama",
		gname: "Midori",
		id: "aoyama_midori",
		gender: "female",
		partners: "",
		mid: "",
		fid: "aoyamas_parent",
		onlineImg: "https://pbs.twimg.com/media/E2e-7sAXIAwR461.jpg",
		localImg: "aoyama_midori",
		bday: "27",
		bmonth: "10",
		byear: "1998",
		dday: "",
		dmonth: "",
		dyear: "",
	},
];
